{
 "title": "Linux Overview",
 "tags": [
  "helk",
  "linux"
 ],
 "panels": [
  {
   "title": "Auth events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "_index:helk-linux-* AND source_type:linux-auth",
     "metrics": [
      { "type": "count" }
     ]
    }
   ]
  },
  {
   "title": "Syslog events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "_index:helk-linux-* AND source_type:linux-syslog",
     "metrics": [
      { "type": "count" }
     ]
    }
   ]
  },
  {
   "title": "Linux DFIR logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 4 },
   "targets": [
    { "query": "_index:helk-linux-*" }
   ]
  }
 ]
}