ca_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDTDCCAjSgAwIBAgIRAL5W0tyXxvLm0Rsvz9aOWwkwDQYJKoZIhvcNAQELBQAw
  GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI2MDczMDAxNDUxMloXDTM2
  MDcyNzAxNDUxMlowGjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMIIBIjANBgkq
  hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwX/bUxVnsoQ057YQtITXbEgNgl+9rJ/i
  zF5+aPDIQKcm40s5c+8oi6owzmPKKf/tADtww0W849CUGiCdq8v4iQACnACvbZTQ
  mhGQZnmYAeHG/JiV6NkmhCr2G+ny1eVvM8CUYXdZAdxBfQArsr5EP+++khsG2aZD
  qkv+MXlDCniY1KHFRTrUkZtTTCSvYgdZqjwIkUKZ7m3mBqilugKcgxv6tjkQjnRx
  dMXtRfsacuCo9M8f/HPuZqosXVvbbP2L8J60D98cxmHdEcCUuGXaQ40TDXpPNy4H
  2lXTMxswzo16bJSY82l7e7tkLCsc5EgxifdE1w6V1PCDL4mVNlWwOQIDAQABo4GM
  MIGJMA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
  AwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUJAnaed0YtRkN3DNQvllyh4Ul
  BjowKAYDVR0RBCEwH4IdVmVsb2NpcmFwdG9yX2NhLnZlbG9jaWRleC5jb20wDQYJ
  KoZIhvcNAQELBQADggEBAK6l+xBv4xLe2T31YTjmOnDXU7uP5IvA+TNj2hBc0yR4
  46HPXerUesbenbX4iibTVJBC4/KMus3qBid3Skp30ez02mqybg6ceZwmTfYi7Ynu
  MYfEXX0EkxelCmrEWuyqSPTvN2Uu32r1icdSdjt1A8EcrTG8FEqvyriSxSmzF03Y
  ruQH5HaDjhwRZvjqMGtdVdRdgLAMgYIu24XREQiTyVNdVr4VO9SwJRpq9UHehA+R
  /qFPGh4yk1eJlHrvKhT0jpn22bStmLdp4d2XVspebR9wSJTSe7zCnai4gnOeepDf
  r7DujRzATNPHMg+SdkBo3+csIq9O6s+gYrSI2R88Snk=
  -----END CERTIFICATE-----
client_cert: |
  -----BEGIN CERTIFICATE-----
  MIIDUjCCAjqgAwIBAgIRAMV232b1hmu0FNZJSvuNt5QwDQYJKoZIhvcNAQELBQAw
  GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI2MDczMDAxNDU0MloXDTI3
  MDczMDAxNDU0MlowMTEVMBMGA1UEChMMVmVsb2NpcmFwdG9yMRgwFgYDVQQDEw9m
  b3JlbnNpYy1icmlkZ2UwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC0
  zl6C9s8io+T1BzkHy5dtLODUeWpT3LvmO5qR486Y2GJrvA4PjNz6iQmDchgtUU3O
  kZhQmD7fuqM3kRbYqBE0MWhMZmljF4e+p5NEvtdv5GL4whrRcv5kRplTZCNltR+j
  Gd3W+X245cLRkLMZ7nCE2cml4DxEElUaAHahJ216wqxsIJGmEziiCtfchWSdaiMT
  2LmjaGKrMhyLedfTKej2RWTrwK8kot9aDD4bBv9sMm7EH9LbiAkGkwgLSnebK9Vl
  TwRuCgn2X8mUa33fJL19wct1giN2KXmM9gA5Z6mXvRNoRX9qPf27rVuVvUy4z5eb
  qNXVfA5L4AUebdhrAbJ7AgMBAAGjfDB6MA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUE
  FjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAW
  gBQkCdp53Ri1GQ3cM1C+WXKHhSUGOjAaBgNVHREEEzARgg9mb3JlbnNpYy1icmlk
  Z2UwDQYJKoZIhvcNAQELBQADggEBAMEBS3jQkh8py7/rSnJA12O4ouWP2P1m7tPW
  SqL+0lb8epDZXexWNxoLLCsnqoiwC3g98S0RFkmb7AgZ8DafeqX6eEmDM1lZKVxv
  aDNi6BVjk2x9GfoGze7DK/NFdFTLa6UvuEOVzTOxYDOO96zBWUiYxegbyd+4QQOe
  3ZhlPf5tW3xl+8nbi3SJorNOC9xv6k9jWkOVBlqqqsgm9Uu6m4KhZw9OI6jSN+5l
  efe564fNQgo+9U0cmHeYTBoVWX6bCqH+gb42BT4mWcanunknrN/74uZnsRPsswC7
  KxKFLeGDoOcDmtwoH+ZIhso2xj8/xjpMvzxo9Srl8ofqvid4/nE=
  -----END CERTIFICATE-----
client_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpAIBAAKCAQEAtM5egvbPIqPk9Qc5B8uXbSzg1HlqU9y75juakePOmNhia7wO
  D4zc+okJg3IYLVFNzpGYUJg+37qjN5EW2KgRNDFoTGZpYxeHvqeTRL7Xb+Ri+MIa
  0XL+ZEaZU2QjZbUfoxnd1vl9uOXC0ZCzGe5whNnJpeA8RBJVGgB2oSdtesKsbCCR
  phM4ogrX3IVknWojE9i5o2hiqzIci3nX0yno9kVk68CvJKLfWgw+Gwb/bDJuxB/S
  24gJBpMIC0p3myvVZU8EbgoJ9l/JlGt93yS9fcHLdYIjdil5jPYAOWepl70TaEV/
  aj39u61blb1MuM+Xm6jV1XwOS+AFHm3YawGyewIDAQABAoIBAAicmbjQK56BQur+
  zJMX+d7r18uW+t8CsPpu1VZkjNcP22Q5QUwxT+co9siJeyhRaozPt3sDPV9notWH
  NhjcrHEZd1fIOvXKzZ7hmWyZUGaWcLZbfG6EdSRujmf/6YWzIk4g8cWG/Zt8ahKU
  O0udZUOWofmiHAy7+Myzv/K+D4NcxNL6iXFNUGgBHR6pNCccOBmz3S66PZX5qmnX
  0WSzDrLEtIeWHYNxZNhH4NI1SqN9Yth2rZy9ao8d8dXiWIXfCN7bSjFxlj/i3LK5
  qlbUOywMw1T/Gqp/PfLlzEJHVnUA9mffU/ggWHRac4343Epqmo0qRgSbCEaTv/V4
  XCpyfJ0CgYEAyaIbgTenJuzy39F4rYY1/JG4vhy8pkBZtXrtNkWsH83Nm7IB3jls
  qBrqYRZSniMdw8eE7icl7ZPsMamtHviILOl6Gj/nNjf+TVb8Q3Tq+nAtAaiBQ0+m
  pLfuEcYSRbLtv67g96l7QEv5Q+i3MT8WEYpkFbmVTkhw3Acxu9NASbcCgYEA5Y6n
  k77azyDwBNsBVLERhi55y4AoPsxrNoNOUtxkCt0l321HJxFF20GIiKl/iTPBcHvN
  sYkzn3v1shrn0hO6mgR9xeltmyhfORsqKz5C8nlPIP/GJEtCidyjSkGq3kS6tV9y
  kTqlQAYe9iOpNRTb2SoXbIIAgvJVKOigPKzcbV0CgYEAr/SmOfo+BOsL+6OJwyv2
  2sSzyju7qP1JC+UNMqpUTaDER5VsqefE2WI7nKPlTxjn9ZycdVN2dr/6g1BFwlwy
  QbcxlcykUZ1Fb2p0U82o7QmNTQAmZX4Rt3bG633FHkvJy9epfJbK9s4V5Vwk2XXr
  JT12n7rG/3yZ+HjSvszYMjsCgYBgqvgqoX5nJwmsIcWnsoEcrkmfxrIr781eQWEk
  R6bhZEtkkRIbg4yVTj1+v1HzpxXYlmoCTzKsAHlwrR/eOWylGysTwr7jTdb7p1LU
  rv1mOmt2C/+WnRLCF2W0CX845lxxsGYAfl/EXE+Be3bv4X7LLox6pywr+HygI4YG
  xwx0CQKBgQC/+F/z60px9FUySb6Kg6dAZJrxZ+q/2y3IgwDsGmT4F1KC4MRSQrVP
  M1RKhnVg8jLmz7NS/g9vQj1uZwVNo3IUqAm6x8/YQ+eY0iaNpSQVaGsNX1wVcEhE
  dqKjgdJgDHZc4eAdFcetqhvOVQT89/CVh9RHquTL1+/1yqGCKr0psg==
  -----END RSA PRIVATE KEY-----
api_connection_string: 127.0.0.1:8002
name: forensic-bridge
