ca_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDTDCCAjSgAwIBAgIRAPLQXHiH5pjCi12kabM+ZQ4wDQYJKoZIhvcNAQELBQAw
  GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI2MDcxNzAwMjc0OVoXDTM2
  MDcxNDAwMjc0OVowGjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMIIBIjANBgkq
  hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr+mt+ugWEcpkw2HH8Q9vUaciVIYndbhP
  ZEy+ZWpyKt1Eg9lRjTWxs7miNb+gyc/N6OwWvJ5fA6+yIGDrjXX0fcW/VkmWmKVI
  AP6YsLcwmjDSGD3rZNW8XVat+E/O79kMgykm5B4LdAFpEcSnDhKDtBiPSqzaTBbD
  amig3YlGDEubC9g+tUSMny5S6ELHS2bAQVIaEHy4EFI+HmisYs8v+lG4jDfXmNp0
  t6ipX6hQtkJnUBxYHgLCgTyx9lPvU5mSbSfWgDDZonuAFQYhotnZ5yNok39QGaP9
  rbgZB9V/4F1nGIcnkVDR7y2c3pctJHZQR4Si0RicT7tb913S7/MMSQIDAQABo4GM
  MIGJMA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
  AwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUfRBdYQdFe02SGmgawHumPo8h
  mowwKAYDVR0RBCEwH4IdVmVsb2NpcmFwdG9yX2NhLnZlbG9jaWRleC5jb20wDQYJ
  KoZIhvcNAQELBQADggEBAHj9R8WNdR/YknuQx1uDxtGK+BkRwxJ1mMWZaqFF+vCy
  bAHS+Z1HKSAdpgSdJdyJgGzL7PhPPLj+fP6b3Tf4mA4Q97Tk3Wr4QyWMKxzrqqVC
  yq78Z8rggz6fnnK4kSFSlXOIqWuPpyYzmhXfrwX59VEFn6DDNz/83gLUKmsHjxE8
  VVwd9GDl0gYWKeSKSfrc0Aq9Xcil/x1lmdInpbgePuHn2o8cQ2kI2+/x7jvY8lYs
  4fcHowBj+p8WjzCA3oNc2SNv/VTOKPjimA+9ekMbzLAbjwp2gW9/Ujwp+azM31aY
  EVCQvR/hvRDWgbSG7Z291SCY/qQGGqSK7LG/EC8iZ/A=
  -----END CERTIFICATE-----
client_cert: |
  -----BEGIN CERTIFICATE-----
  MIIDUTCCAjmgAwIBAgIQT1iXbo4WdY20bpmClV0CezANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjYwNzE3MDAyODIxWhcNMjcw
  NzE3MDAyODIxWjAxMRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxGDAWBgNVBAMTD2Zv
  cmVuc2ljLWJyaWRnZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALKp
  r98cDFKWCE8eEJtvLiitwdJ088XTs5cs/EjEO3D67Cm8EO5O4HPRBr6/6OxG5xuB
  mwZv9OESylsuqzljl5x0TxBg/28JGvpEu1sTuHPOLBbDpWri0YQdyssstaQw4pLa
  2Xlhd1cc1NUxaGj61csGnurzz+n3NWIFz+gm1+/IKNb/nWmwju0qNBngvErzIws6
  3LIeq7/7Y9EmOH7Z4yHpGg3KBlT+3kJA2vFtXKwNisY8oQwo7GNUxbzUIUxE65zF
  mkUH1LDe1A205v1uuDR+CR49Vn1g+gLnG0xq8+1NtxOcCXfAotn2aHLwWeI7ptJI
  nipD3rwJVVyFwVlXg7MCAwEAAaN8MHowDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQW
  MBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaA
  FH0QXWEHRXtNkhpoGsB7pj6PIZqMMBoGA1UdEQQTMBGCD2ZvcmVuc2ljLWJyaWRn
  ZTANBgkqhkiG9w0BAQsFAAOCAQEAc5YGVWb8dtNUY7j7iubNZWXYVZqvaPihd3JO
  q5UOoBOBQ1Uwx6/r4Tr0oIPDX4gbsxaHF7NiG3PrUoTMQ0eMh1TkxV6A8SeKDOj1
  yFEcr3Gp7OOR49Kc7nu587OkBTj0AyUD64pVVfBKxCZ6vcz2tu3g8d3bdRDJbpZJ
  r2d6pbP0HZwe8Kr9tmrdwwTw4Q4wfTcnYvj6VAL5UvEMjy+a5KOI4aRXTjryp408
  PhvCyU32cEnVjeG5M2o6Psv8sD/NPpSZm0bBMpWHQhCdpWd/ROA4EI20LPOMsdME
  OSu1Nd2b8RlulHz0/OoNrmubXK9TgeHdWxkaX20TRh9ky/8hHQ==
  -----END CERTIFICATE-----
client_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpAIBAAKCAQEAsqmv3xwMUpYITx4Qm28uKK3B0nTzxdOzlyz8SMQ7cPrsKbwQ
  7k7gc9EGvr/o7EbnG4GbBm/04RLKWy6rOWOXnHRPEGD/bwka+kS7WxO4c84sFsOl
  auLRhB3Kyyy1pDDiktrZeWF3VxzU1TFoaPrVywae6vPP6fc1YgXP6CbX78go1v+d
  abCO7So0GeC8SvMjCzrcsh6rv/tj0SY4ftnjIekaDcoGVP7eQkDa8W1crA2Kxjyh
  DCjsY1TFvNQhTETrnMWaRQfUsN7UDbTm/W64NH4JHj1WfWD6AucbTGrz7U23E5wJ
  d8Ci2fZocvBZ4jum0kieKkPevAlVXIXBWVeDswIDAQABAoIBABBfL1AVHGX2/KTv
  Xts3eXXd0kyMTghbSXI5e5bZcI7+V2TNqImF7dh/F4ykPl5kcuoY2tFgsgJr++IW
  KTeVkj+Sguo/0ThmD7ROVxLWAEmQY4bkf8SHK2bdagdrPevhVOnbJyGR1mNDr5cn
  s2cnUS8NGMPz+qH4dspYOQCPiqsct7I3gO4GolnlumIo2vivHMPACd7R0eIn0Jii
  uPcyxybTw31NBR+spbWyBGqt4u6e+ZlSGzzUAM6NwqjWXsTk/f3iwsL69Z5noiwq
  DpK8VnY2Pw8S2j4oMOuW0avKj1qddGLFXhhvLC5sTYj9cnF0ZlV3C3hS43Pyi+U5
  9Fx2x8UCgYEAzPV+VoStk3aDTDWqOXTtWYNLnaQG9RWlIKiq9DTpaqqr6MS2NSAU
  tOAgD7ZU8kUubICWOi+1dsyd+8HHCgMKY5XGLDwNS46CBavJjweoM+9WgrRc+RPD
  8viKOfTRi5vPPcrG2eWLLJ3qd0Zd3m5qXysvy/2KMbCV1v0RcNESvfcCgYEA3yfE
  n02Nl1R2FdPVcUWTUCIraPbJ3e0rJ7VEUMLBwdLJD7wbiTjCzM2KOnsApWB1xq5b
  HnYBs6xjJQH6ExNxWvQwMINf1f9gNo04GxNMghKcSrMzHOUxj191Zr2TbvX1nitH
  8es0LZfTFCM3WOgtG9Za1SSW5r+IC/3NCkkWqSUCgYEAjADZtwHUi5l14LX7vFnJ
  085i9aDY+8s4S9HLTRtjonBJE6xjhnCOlGtQm0sCRafKKWXAuKhkPW1SMWnRq14e
  V540i3zN3CHRYUxSV3h0hl1j686Gf8HnpO3vhd1c0g+xhdUg9jDdW7HXOnh/oHQu
  Byo58Q8UuhKUmBGwOy8lrUsCgYAf5Rg2SKhfI8RI9GECcpZOksOvme5aWOadI0xj
  WqLE6DKynAk3gLRe/1WtbB04hePvhMYjQWyW2KHHDVRH27SM8m/czzooZPrEcUS+
  ofCCetR53MkGbT+7JUKrb5cd+eukMr1yt1Ja3eNecnYbr/uaifWrlzI2QtPYGutu
  d+nUPQKBgQCbZhZaqAsSGY9wzBeCinnAOmdCz4Ah7TTD1MSlwEXPwwEn3GQWukHT
  FWKdw/K4YJ3Ak7L0GeRtTgWMuRfovpNTyNmZaZgdAEm1or52H5bC/dToy2aWgNTD
  RpWghlmgD0K35iPBRPnRRT+1Ao0zj2Ttj1F7AUB3dTrShHblz2j9ww==
  -----END RSA PRIVATE KEY-----
api_connection_string: 127.0.0.1:8002
name: forensic-bridge
