ca_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDTDCCAjSgAwIBAgIRAIjDgp4sTf072r8RbJS39AIwDQYJKoZIhvcNAQELBQAw
  GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI2MDcxNTIxMzc0MVoXDTM2
  MDcxMjIxMzc0MVowGjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMIIBIjANBgkq
  hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvy3QHcTUd3TqKp1rr9g095G/gHBF736b
  HDNEWj7LuTHbRy5u7Bwh4OCCswF6NuFFIlFp9II80lgErIDfZT2eMcTj5r7Lhp3N
  yGYhUnvdKl4GeDu39zlApYm4DfimPLT25N0Fj6SG46oyhg/FNjsgKvT8xvz8oRXP
  pAjWUFqgGgSOVubQa6y83zoqO3gdp8FicqUiwtuarjZsgkqBdNlC7OktKkqKqivd
  pg/hf/3VTntchHhhTj5X7NvQQXMVLevs/2soXFVCceIGM7RwhSzKD4UyiaqoMnDM
  eb2GGMU11YLJt/1iquVKIgcfF6kv6faxtLqBhYD5kM9/5X1AK6RrlwIDAQABo4GM
  MIGJMA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
  AwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU8lDey/1UXz+l1/9WeqzucW4/
  M2UwKAYDVR0RBCEwH4IdVmVsb2NpcmFwdG9yX2NhLnZlbG9jaWRleC5jb20wDQYJ
  KoZIhvcNAQELBQADggEBAESUoalqIifB4svlIjhtHDln3HN5S55XMffoM1q9dha5
  J75D2yHjbcPp55PoJIPCzY54ikK0iWaKaGj1+MM1IIzzcUf5Qt7jxUxwWnBfc0QT
  SkCMxXIx3ZSo+3A1IUQ+NRnFm52wRO3VdWtuYPjsfCtf4lmCj8PHZu2IhKRCUPGy
  iVW3XLzXufV0J+uMPeIxp9mmm+Ll0CoYMgsmulHzsTd91790G93BD8PEaq4RZgkG
  gSYDgZPKe5fIfmZfKD/ADqZylDdKnAW9dmQqOlgFYE1vAjPjZvu/XbNdxOWwJm7R
  NjXOh/30VhCcxkKAYJJJbA798JbLEvcy+deAV5YY7Wo=
  -----END CERTIFICATE-----
client_cert: |
  -----BEGIN CERTIFICATE-----
  MIIDUTCCAjmgAwIBAgIQec5zIzkthThYcMCdvrgbQDANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjYwNzE1MjEzODE5WhcNMjcw
  NzE1MjEzODE5WjAxMRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxGDAWBgNVBAMTD2Zv
  cmVuc2ljLWJyaWRnZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOYh
  xW0EFLeYU9z2QYnght2QJyCyWUgkPKJ8mhN2qgxhw5Mi67+eeQNNYsve6yQ11R1v
  1nVT88P1QjyfNbEARRNv3vVwKOFxi+EemGYT+O2dS9N9SAT+I+SnN9d6J7XxPiEE
  bIGerQY1ldBUk0PFvR2mfX37cZ+6HregJjPu8bem4ZMCajmW6Cmuz9iXjrivhZ5Q
  JtL4qW5rJwSOMeL1yhlTNSEPP1WAL8oQ7Zja9ExLqsLPmEIq1eZwmJ/t7oO3YpFM
  ek602ZFUwfPjFbf0gtUw19NceBKdp+ABKFfL0A/3k/h4tEecaQTV/ovCuhTswOCK
  x9xa+YESnVbCUXlE56MCAwEAAaN8MHowDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQW
  MBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaA
  FPJQ3sv9VF8/pdf/Vnqs7nFuPzNlMBoGA1UdEQQTMBGCD2ZvcmVuc2ljLWJyaWRn
  ZTANBgkqhkiG9w0BAQsFAAOCAQEAXtuXkTNWtolPBFsw9fzKKtAxJoS12AD6gwAh
  myRZ1jJcZfJioMnIooYJ1TV+GH/87Vod84gEBZYpR1/zoRy5W51CwxIxGpaUBH02
  RnGHkqYN8rCsdxVFr3xvI5EV6NfBTJdNxJtsVQRqhqe72G15KIx/LrW701Y4N/Yw
  xP35b0DLiyk+cl2+f9javgCLShZLpMN2b1MvJUn7k2OU5lHKtmDgOP+B1kFjGmcm
  7tqV/r/0tY4Ve5a+0CIDG5+wSpEuLKaNn3JW2UimonsDKLBey9dcqcYMHQ+aKS65
  F18f4mGYvh/LwH8L+NLV3uyOrwmJIFCvKN++kVjUML9jK0W2FQ==
  -----END CERTIFICATE-----
client_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEA5iHFbQQUt5hT3PZBieCG3ZAnILJZSCQ8onyaE3aqDGHDkyLr
  v555A01iy97rJDXVHW/WdVPzw/VCPJ81sQBFE2/e9XAo4XGL4R6YZhP47Z1L031I
  BP4j5Kc313ontfE+IQRsgZ6tBjWV0FSTQ8W9HaZ9fftxn7oet6AmM+7xt6bhkwJq
  OZboKa7P2JeOuK+FnlAm0vipbmsnBI4x4vXKGVM1IQ8/VYAvyhDtmNr0TEuqws+Y
  QirV5nCYn+3ug7dikUx6TrTZkVTB8+MVt/SC1TDX01x4Ep2n4AEoV8vQD/eT+Hi0
  R5xpBNX+i8K6FOzA4IrH3Fr5gRKdVsJReUTnowIDAQABAoIBAFTQE2uW+m+jUxz3
  ILZIqkuTqefx8teUi0gy9bHApPEFQsfCMfIf3GdsKMIL+MsSj+VWZ0o8U3VfuTaQ
  UoBWIh8Etr3rxRU4/J1N4kqUh8RCmURrQpSceOv2+KyQF3yFWSlf8QFgUlIcg4cQ
  9Gkgwg7gYhWBCqIcPN/dxNaU9D6DLmN81uilTshDYwf38pqXRD78a8OqXJu19JfL
  bnHSJ0BYfhQ18gTT7NYJ601jA55dbysMQ11HbWBgZkcWE+E1otXixwNnBK8FsNXh
  05Mn32RrrIlW6ayW6TatxoswwgkVPcgUczXskVVFpmA5NwMEOASU8zZK81ZaECxZ
  4kuypkkCgYEA96oRB+13CayeR9wXJSAFc7gSJqpzqaZSaOwtn5k2Tt6x4/QD7q1z
  bGgZL/scYh33NDGG846bbhQkn65cWazG8T7JmwRFQ49owYz3/hO4/vUDpjUgZO2x
  C0Od7f9QG5B4cedZk1vACnZFsLVmI7gLZJNueQzYddGWZgYENF5oiB8CgYEA7eCk
  MngWVgItRdgdeXUdyDDKBycbx2zq0D5XyvgpDualRtLjVTSzUiySc7y7mmxNY03I
  vVwZQB6MjnBRy+CvV7ArQCS2nsXEnei9Wjbzd5659fzI0e7qaMOzJIss7iCD4gYT
  K3PvM4QB1a/0ct/ksDSuFFUxy6vd3t9EoW2xf/0CgYA79h3XeIO4gOV1anDkGSOY
  x7kFSYFlUpJjOsM0/8gpQjt5gCuvjqkCVxW6CybtDmo6Zb9RmnZBKXlQe8t6Hp2v
  7M6szFTkrYTkT3f/ONEyUSnIBNbJ+M5DduR2qbjAY7L1iNikF7OgFNB8nv6SqU2A
  1T0K67RAmjS6kLxV3YGbawKBgEPF7QI0FKkMlbmAiWVBaOrQe77t9YwsC/qoyHqb
  mZcVP6GeFAcCrNSMvm0bKJgmoyXX04mf49HQ4lryxVtA+LQTDT+JNj6mOg6DcO9z
  GIrMPk9HZi/p0f9nQnL29CYkPW74LB4FOfGDesJXD15rS8yoNbC1VSqiHOSS2Arm
  JdxBAoGBALTO99y2gPXUziz1HMbdFkaDh59FrV6FQwOR39SBphf1qHBaWThE6lFq
  cyzOa5mYqETqAgzM+KIuAqAdVB5p5pfAQ4OynpdJ45LQ7+abHWnBjOBnGv1zjcmL
  3MekjducGPdOk1XBaPr0bTZV4FJ+PeNKCO2gjRiw8GAqmLLVljku
  -----END RSA PRIVATE KEY-----
api_connection_string: 127.0.0.1:8002
name: forensic-bridge
