version:
  name: velociraptor
  version: 0.76.6
  commit: 20c779e55
  build_time: '2026-06-03T10:53:44Z'
  compiler: go1.25.3
  system: linux
  architecture: amd64
Client:
  server_urls:
  - https://192.0.2.67/velociraptor/
  ca_certificate: '-----BEGIN CERTIFICATE-----

    MIIDSzCCAjOgAwIBAgIQfJwEaV76fSGOmY7pDdcP9TANBgkqhkiG9w0BAQsFADAa

    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjYwNzE3MDE0MjM3WhcNMzYw

    NzE0MDE0MjM3WjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG

    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQD0dqSerkrPIVcQQ2kQ6BubpiJEi5A0gLnV

    u2bt5WQkWL1exTd5nwLvITwpJYOn7CLd37xmpLGEJhf8zh9cfqw3tPMiobr7VBzk

    TMqfW4hKWtnEXu7OlsAtm8gHazS/9dOHB9fYgpaL0xY2P3XWMNCFYk366LaCermL

    U6IuIkDfuRtgbTeXK0npHThpk5zvuQ69eCxYJ1ZvTpAP6T0+vV3vT+HU1YH0wXfM

    1AJkYrpqG2n1t+puzMG4X+6n29OvNJZ4V1mKwKButlMgPyWXOFMdw0y7z8LjN4mn

    IBU/au1iqQhvfls7U+jkql9K4uqFxoK/nI9m2HJskUL4J9B1titRAgMBAAGjgYww

    gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD

    AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRsz1pLterGgCwJUKbZsafe/qXR

    STAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq

    hkiG9w0BAQsFAAOCAQEAZ0lmAcOjQEriqmWe5fRHkespkr3FcJZne4V2Ug70k4NV

    qFSfXdiHN8/NJysP2iDaM+vil+qMZt5CU4NHPMHHZSmuXToxqiS7aQhHAgDSX/ko

    Qauklv9sxL2oO3mkG7i5N9kxB7TFJVN+RJp65ljz4chGpOqHl6axL1eZVKrLUGVd

    To2PfFqof/Lleyx1rlfnCjZOe6BCdYnsiWnPTTw0S0O+hsvcW5uvbIVHTS6H6hP9

    +/zhbYnOCHKGgEpczmEmhILHXrptg3ka0r+ZSo3fafkgUWgblJU+MQ57ckXuF+9q

    vB2sKp1nGTcQZ8y5LKCgxUf/ohC1n+Tgx+DWze+7yw==

    -----END CERTIFICATE-----

    '
  nonce: 201Vuc9jojI=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  level2_writeback_suffix: .bak
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/bin/velociraptor
  server_version:
    version: 0.76.6
    commit: 20c779e55
    build_time: '2026-06-03T10:53:44Z'
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
API:
  bind_address: 0.0.0.0
  bind_port: 8002
  bind_scheme: tcp
GUI:
  bind_address: 0.0.0.0
  bind_port: 8000
  gw_certificate: '-----BEGIN CERTIFICATE-----

    MIIDQjCCAiqgAwIBAgIRAMggUcO7Ry8N4zYAIWZaivIwDQYJKoZIhvcNAQELBQAw

    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI2MDcxNzAxNDIzN1oXDTI3

    MDcxNzAxNDIzN1owKTEVMBMGA1UEChMMVmVsb2NpcmFwdG9yMRAwDgYDVQQDDAdH

    UlBDX0dXMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4bxCYLf1X7ng

    YRY/eSwoX0Ou3me8f96TIQCUvEj9jNLXj720duueNuLPWw6QazyHeKzPwNY9cNeA

    XFTFk+aQkVjFX2/mkX7PqaFBy0ijfBHkR4x0G0/7M97rfMIfq3TK83qArQvx7x9S

    +P4ekF7HjX300PUATO7zYkDsK434VvHX0cT2RNGrFgu8ZqVfroJ/RXAXi/gBCPg6

    S7u+6cN6KTX3TRb8+N5kVkxANrtPpgQ/s3eMjuWEADGODYMpae7FZUsq3KQEhXIK

    ZMmWgnC8TooAne4ze/CqgPFnHtd8TEEJzfWXNGfQLfkhQ00AZHcf9pwDmnN2pVyL

    Y9neutLlKQIDAQABo3QwcjAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYB

    BQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUbM9aS7Xq

    xoAsCVCm2bGn3v6l0UkwEgYDVR0RBAswCYIHR1JQQ19HVzANBgkqhkiG9w0BAQsF

    AAOCAQEAZ675BzUtejaZZI0DoY1BItDeusWKO4ohiDQIWIe0oAWRvTgenddvRwi0

    7Wco+4IITIiiLCMpcwssgRV2PykHQ6sV2Ljg9UI+rn/nwA367dKJxXFKOi7ac9Mb

    GHraKUAeLLj1Em1HqXXZhnCNuYp7S/698qDM9UKeVGMJCNZG0T6V6Y/x13nqDeTu

    OTukQvPtdxVmadsmD44G8dyTST0qjh7MICpZiZIg8Mo83qYih0Px0dkF0P86Z4IG

    EDsNW3lvnbcGytOnWP2iL5zDlpg7rd4DxhCITmH/i3UGiqbVptQRIf4FpwiuEe60

    7IEsdUv+KBjgCm+g7F538buDA9YwHg==

    -----END CERTIFICATE-----

    '
  gw_private_key: '-----BEGIN RSA PRIVATE KEY-----

    MIIEowIBAAKCAQEA4bxCYLf1X7ngYRY/eSwoX0Ou3me8f96TIQCUvEj9jNLXj720

    duueNuLPWw6QazyHeKzPwNY9cNeAXFTFk+aQkVjFX2/mkX7PqaFBy0ijfBHkR4x0

    G0/7M97rfMIfq3TK83qArQvx7x9S+P4ekF7HjX300PUATO7zYkDsK434VvHX0cT2

    RNGrFgu8ZqVfroJ/RXAXi/gBCPg6S7u+6cN6KTX3TRb8+N5kVkxANrtPpgQ/s3eM

    juWEADGODYMpae7FZUsq3KQEhXIKZMmWgnC8TooAne4ze/CqgPFnHtd8TEEJzfWX

    NGfQLfkhQ00AZHcf9pwDmnN2pVyLY9neutLlKQIDAQABAoIBAAktgCs3mNLNkf4P

    MLa2nnAWxoGdSQclDPPngVnr4598ft47CGmu2qHbjsfCbnRRCPwq1i9eY9pbr/4h

    BgpFZ9KO//GpcSqFyT/kchI8/RpJOHABGa3hbo1NS+NTRFodBMze1Hk5/iTFRWMh

    TYERZ26Hui1zjpxHeU6rpNErA8zWE1pmjvaqSWM+2D/GhEZY/ScTHXEi41GuwwT/

    rGzDxgYQoJ7QvvG8q6DWzFqcjhf07aT//+/IZMBMXLBhYvmYGHwxIJ+kHGCSgZ4C

    EVu6EdF/uzcPNEmR3xTqS775vuSGk3HhW2xckn60P3zrFGvd5EYxd7bXG68akmqe

    zXCOZvECgYEA4f10Thzn9PcaNVDN3XK43n03WiKTO34TfQX39Gi4NSPTtR06/n2j

    1TsjvLk2Hw54zN1bA7p5fbVgijSrHz3nEm8x6YKT0kT2U9m71t2UvdsPyeya/iro

    SHqy+bRChBNYZYazq4GITEVnhnBgzhDYz9j9rmRBh4dyM3NTOPnbXzkCgYEA/7Yl

    w4MiNA7iZWkz5sprgk/N0jM8HI2YjRz2NeZLLUYLescMdbKwnzzvrH7i1ztMD3Kz

    0CjUXEdCPhL8qrOmwA1ZskOWO7zkwSuWfpFd4pcd9acnFXTzO0QXx/huhxL3LRZq

    53p16KybDMRJ2cHXFrKiTxTNLvWaSzT6wA9vxXECgYB+PBW7jGoFbAI3xes4x9x8

    a3V/49BaaxJ3w929qME87cZUZP+PKJ9bfK15vft9XZgc14j/jCpRDf/fM4xi5zEs

    GvDGfyoTSnJOZFGItD1hz/wBzyjE0TLvSZqv4QFGxYebLqMuKiz4bcxmTF/Gu6Jg

    d9U8lMQF8KLaGpFiQi9IAQKBgQDaSxnD5Q9u14IHxp6LGCRdM1lmZ1yal3oyhRXe

    f4GP3arxHjmRxICo/7EvVYa67KEK0wWT3zciq6ZuLXFLHGButTbsSmxXBPNXwKkR

    1XELfawSyKZB1/vIjWGr0XYxk0w1TlzmzREZFzip1muhHKxMcSTEU+KxgvM73rds

    /ACT0QKBgH7QRC+WaMN6c/E/RDYp6uEGQ0ZIL89s8yjI/RA4C8/ADm1ngSJV9VaW

    PHrON2j0qU/TLFABpN+hrC5+mfDZzw16UQKIWMAEz/3SCu5mfPcLhVKszmV282ip

    zaQM2Vr/ovGxUGjBMEVxXsMdrVutYOVqi7OzSjhTZc8WXDH3+L3g

    -----END RSA PRIVATE KEY-----

    '
  public_url: https://192.0.2.67/velociraptor/app/index.html
  links:
  - text: Documentation
    url: https://docs.velociraptor.app/
    icon_url: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1MyIgaGVpZ2h0PSI2MyIgdmVyc2lvbj0iMS4xIiB2aWV3Qm94PSIwIDAgNTMgNjMiPjxwYXRoIGQ9Ik0yNyAzYy0zIDItMTMgOC0yMyAxMGw2IDMyYTEwMyAxMDMgMCAwIDAgMTcgMTZsNi01IDExLTExIDYtMzJDMzkgMTEgMzAgNSAyNyAzeiIgZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIi8+PHBhdGggZD0iTTI2IDBDMjMgMiAxMiA4IDAgMTBjMSA3IDUgMzIgNyAzNWExMTMgMTEzIDAgMCAwIDE5IDE4bDctNiAxMi0xMmMyLTMgNi0yOCA4LTM1QzQwIDggMjkgMiAyNiAwWm0wIDU1LTYtNC04LTktNS0yNnYtMWwyLTFjOC0xIDE2LTYgMTYtNmwxLTEgMSAxczggNSAxNyA2bDEgMXYxcy0zIDIzLTUgMjZsLTggOWMtMiAyLTQgNC02IDR6IiBmaWxsPSIjYWIwMDAwIiBmaWxsLW9wYWNpdHk9IjEiIGZpbGwtcnVsZT0iZXZlbm9kZCIvPjxwYXRoIGQ9Ik0zOSAxOWExMzQ3IDEzNDcgMCAwIDEtMTMgMjZoLTJMMTQgMTloM2wyIDEgMSAxdjFhMjUwIDI1MCAwIDAgMSA2IDE3IDUyODkgNTI4OSAwIDAgMCA5LTIwaDR6IiBmaWxsPSIjMDAwIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIHN0cm9rZT0iIzAwMCIgc3Ryb2tlLWRhc2hhcnJheT0ibm9uZSIgc3Ryb2tlLWxpbmVjYXA9ImJ1dHQiIHN0cm9rZS1saW5lam9pbj0ibWl0ZXIiIHN0cm9rZS13aWR0aD0iMSIvPjwvc3ZnPg==
    type: sidebar
    new_tab: true
  authenticator:
    type: Basic
  use_plain_http: true
  trusted_origins:
  - 192.0.2.67
  base_path: /velociraptor
CA:
  private_key: '-----BEGIN RSA PRIVATE KEY-----

    MIIEpAIBAAKCAQEA9Haknq5KzyFXEENpEOgbm6YiRIuQNIC51btm7eVkJFi9XsU3

    eZ8C7yE8KSWDp+wi3d+8ZqSxhCYX/M4fXH6sN7TzIqG6+1Qc5EzKn1uISlrZxF7u

    zpbALZvIB2s0v/XThwfX2IKWi9MWNj911jDQhWJN+ui2gnq5i1OiLiJA37kbYG03

    lytJ6R04aZOc77kOvXgsWCdWb06QD+k9Pr1d70/h1NWB9MF3zNQCZGK6ahtp9bfq

    bszBuF/up9vTrzSWeFdZisCgbrZTID8llzhTHcNMu8/C4zeJpyAVP2rtYqkIb35b

    O1Po5KpfSuLqhcaCv5yPZthybJFC+CfQdbYrUQIDAQABAoIBAGjE3CJhghApMr32

    lfW38/UOC0ujIIdPz9UIvsEf+X4WRfpyvSazfjdr3/OmbzktW3gJZh37YVTIWqlu

    0UP7yeUJ+NWTyKXj04oIWyJWwR9UtlWRdfk15GDnjZ+YU4AdY61QMDJLLSf5rGBN

    bDwCqaswiUkKKQXcgN50VmI9Ld5zCRke7e94tDPkFZ5l5296vwyZCEclzZ97sAGe

    rQ08UWwrl42BfVcDC0LOtQlaDe6suEwTKbiU+LV+lviZAfyWQid0DrjOgpuQzyM8

    iOI8pdYfJeAZ4QUAWRzzlMby9G3RBc+1Y4ED3jwvRb18O16iibroMna4euhBTabE

    vpvuyX0CgYEA+NNA5WbT/Z7+mV68kHneGkot/9aC3REvdhEBlhBLwuizFRJUWQtp

    i3QX7dP8YxCgIXm8ij6VjGstzS9d2KfsyallVC0F3II86fSBuof007Tw1I9adkSs

    P4j3pmxnFiuu5FWIbzZcm6KAynpi6IW9KNjISjG4JNetX2ADdeZK6BcCgYEA+4Mx

    RQ0W2iI2q30IA3OjiJ9LQnYxog1me21k6sjlNVbwU/bEU4RzfgHkRIrdzYf1s2P8

    //7vqAygLz20G0LZ0TjyDkpeP754KjK3LHQ2IEF74/W8nD64OSAlz3X8QQJffSvO

    GT33BqzMQhyBpADNkMtizygjc3IgHBE78FCkwNcCgYAw5OIlsdUKS0ngPVt0UF4y

    cE0lrrM8WXooCyNyp3Ubsbou89EbRkDRJFjnZPZ9SPEOYuuHhtDALPdtEFeykRzY

    a677oXU7ZWQu3Nr5Gmojh7SjMCAoiUoHmhR/4WFIXAEb4SrUH6yG8KG6J95zroQD

    GMYSvj5fDvqEeUt0yXICtQKBgQCaLyLVIeEQeEjreAqhkxJ9fqm0ZKCop25b3AQx

    qlZZDKLn1i8kw93JMX+uRTMT/HUzM+i1RqPEcXkBfOIclC7ThAVfnVeJ3EnuFIkW

    R2em/n3kkZC+d/SXkI2dUMcDU2EWavQ9pS76eJP/M1qGH7flO8mnFQQmkZ/9lNMZ

    z1YwoQKBgQDjQoXxGHM8ksI5dY+kiXful+R4rohn5I4LVnvZFOqNhPF5FLbCZhfq

    JhcM6Tu9wg26t99KLHfQG0SoPLAtwqnZy+7FdM43fLd6jVR1U5yhJfVjCGCBQfAz

    PpNVeMc734XyQQerHX6Fp00mnX2O+aLd1HD8j3zlcosx4OJ040YbeA==

    -----END RSA PRIVATE KEY-----

    '
Frontend:
  hostname: 127.0.0.1
  bind_address: 0.0.0.0
  bind_port: 8001
  certificate: '-----BEGIN CERTIFICATE-----

    MIIDVzCCAj+gAwIBAgIQW0DIz/B9SjyRg43uMYE1cDANBgkqhkiG9w0BAQsFADAa

    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjYwNzE3MDE0MjM3WhcNMjcw

    NzE3MDE0MjM3WjA0MRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxGzAZBgNVBAMTElZl

    bG9jaXJhcHRvclNlcnZlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB

    AL3UpmfUmyyp6AmZqxBZKa2yszrQiG2rYZ458k/FRVhmtHr0EUYejoW2tQqbQLaF

    N6f+gGKm61nKDK1jvcNnCKxsyiyGg5qQpsFBeaTXttlmjwPgAoyObSMt7Iva3zh7

    38MRtbe6fN/VA4Rb/wFMqGq9SybccLYOcQpo2qI6yKTvdE+xknfUa+3zqKwcPKP4

    wpK0ObheMZoN5Tg9LKsHdZiA6Tv6Evmii4pfIvpqHhlKbfiDPB3/GwctCiltbq1o

    Hp/oPV/QE7rUS0vFjiVrTVP1bDWymovJDVNvuF9/MxFmHO58H6MQxVYVi/+5cJxL

    0uzarmHDeH6JoLBgXc1Ao+0CAwEAAaN/MH0wDgYDVR0PAQH/BAQDAgWgMB0GA1Ud

    JQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB8GA1UdIwQY

    MBaAFGzPWku16saALAlQptmxp97+pdFJMB0GA1UdEQQWMBSCElZlbG9jaXJhcHRv

    clNlcnZlcjANBgkqhkiG9w0BAQsFAAOCAQEAP4BXVK8s2qUhupE9deipDW91wDKK

    qQWKgAb/jKnFPOdHFYHsa+DaFKmxJKDimiUoclloiFmpeLdO7ohApZTRMNWWUNzG

    +8KpRw0fSHaeIJzCcgqgX52BBv+EwZdQt9ACDCz28hcnyJbkUINiMCA2jYlyIhB9

    EesSqEtsNvP72dtHqIKx0lunqdX4A0p1AGkLN5brILfli1GBt+b4JR15ULYoqU/I

    F/NqGzmbNuuQiASKwczA0iosZk5AuAdz0Toky8s8/Y5NjkaEhz1Hxmiyd3q6dUPi

    ri5tBAzx3JkbMJ+YYDHy+Kf8n9/WsueZoY2vz2pqDBT6/FyYmCeHuMz1ZQ==

    -----END CERTIFICATE-----

    '
  private_key: '-----BEGIN RSA PRIVATE KEY-----

    MIIEpAIBAAKCAQEAvdSmZ9SbLKnoCZmrEFkprbKzOtCIbathnjnyT8VFWGa0evQR

    Rh6Ohba1CptAtoU3p/6AYqbrWcoMrWO9w2cIrGzKLIaDmpCmwUF5pNe22WaPA+AC

    jI5tIy3si9rfOHvfwxG1t7p839UDhFv/AUyoar1LJtxwtg5xCmjaojrIpO90T7GS

    d9Rr7fOorBw8o/jCkrQ5uF4xmg3lOD0sqwd1mIDpO/oS+aKLil8i+moeGUpt+IM8

    Hf8bBy0KKW1urWgen+g9X9ATutRLS8WOJWtNU/VsNbKai8kNU2+4X38zEWYc7nwf

    oxDFVhWL/7lwnEvS7NquYcN4fomgsGBdzUCj7QIDAQABAoIBABUxStyXnzVGyKld

    tvvNwHnsU9cSldCMjArilDs0nk/Gs4pwegc2fRnPcnm7KGfYCoUeRA3/bZHqHS00

    T+ijNZQuVwnOgJ2+XWeA3Eg7buXpbbj0hsRTWDrPszNP3ZDMP4hjD0LyNmO0v75E

    mPz3pmu4M04k2Q5yIUuUtifbYTAMfC6pQAFUw6vVjm1niHX15dPc6YJD/kLBe3ug

    u+fWO10q/KiLSMkE7YZU7ShpFkIz0jCJH2xV0wuitSTtJq8k4Dadgf0KaPPmhCkt

    UuYsFJ5MLqvfedcCiR97osBgUxPJEuxPWIk/dSb0FNXMnNo6kp3amWdcb/q2Ch1k

    lw9/hnECgYEAytG5x2mAh/8d2aEH++rTl2+HsltWHQV7ag0yTZYov+K/Jq4TLuTM

    SkUNdFPmqP2tUqI+zRutoBu8SlySTjSy76kg4hwJL+Q0jMt7N+aHcBgrQe2rzTEL

    S1wQZeIrSNjrEx+uAN6m+laQej/Q8LfgXjZCBEpLUU96xISG4/CLXLUCgYEA75sQ

    YoouRtO6WbUp/GgY4Ixg8oedFPTfPVIMTgfL7lOL/MISuJ0qa6JFKAjOxCgDwIJu

    NmFSx2huZSfM88ebVM4qcWBZbQVe9Yhfm5hFcIIbnyBlWoUMO/lFLUufZ/x37zhO

    agst9u4xHqFCYc6STLAdofVBWQVij5B4zUqSZVkCgYEAyHkzI9uxsztFOxdDuAsu

    KJKSU4aagMcpbPMsVKpnDvxGqyoHRiPbllHY8bH43fMZPgOnBcAlB4xCulH0P58x

    e1j2aukBX7g3BTAgVGnmV7NcFqehWInwuwV+I+bBmBjpixaWPL/X1rx3xI6NrVJj

    UVxaNrlk5zMji1nfpzDd370CgYEAovxz9NPSDtPPm14kpVGaOoTDHbcqHytC/89k

    F2AuVHv4aYMKgRJH3NeQ+16iZ8RgaP9QQSWKzaI4Fg8w11McUl+7d0v3CLXylkqh

    3pGCCro2V9QNnbmLTPCPIfSjBnUykENY88GPDr2QJCnFogqGciwKvDS8svV6yfWY

    du0XEGECgYBb0lHmp8xqapt8fAe/4cm2SnnAVs0mPuOw9rwkS1XDWKJxPhcCYUdI

    tmFppngL3btpRkGLTxF+h8y3LjEy/q4CUtoEt5BiFfLb4Nz7TxsKIkNiTJrMTB4r

    dak1tQdU1o4AozIkKBedDKZTlFa8N4HRiiAs96JARgZoiQ4tEzQy2g==

    -----END RSA PRIVATE KEY-----

    '
  dyn_dns: {}
  default_client_monitoring_artifacts:
  - Generic.Client.Stats
  GRPC_pool_max_size: 100
  GRPC_pool_max_wait: 60
  resources:
    connections_per_second: 100
    notifications_per_second: 30
    max_upload_size: 104857600
    expected_clients: 30000
  use_plain_http: true
  base_path: /velociraptor
Datastore:
  implementation: FileBaseDataStore
  location: /data
  filestore_directory: /data
  compression: zlib
Logging:
  separate_logs_per_component: true
  debug:
    disabled: true
  info:
    rotation_time: 604800
    max_age: 31536000
  error:
    rotation_time: 604800
    max_age: 31536000
Monitoring:
  bind_address: 127.0.0.1
  bind_port: 8003
api_config: {}
obfuscation_nonce: /DfwaCbzJdQ=
defaults:
  hunt_expiry_hours: 168
  notebook_cell_timeout_min: 10
security: {}
