version:
  name: velociraptor
  version: 0.76.6
  commit: 20c779e55
  build_time: '2026-06-03T10:53:44Z'
  compiler: go1.25.3
  system: linux
  architecture: amd64
Client:
  server_urls:
  - https://203.0.113.9/velociraptor/
  ca_certificate: '-----BEGIN CERTIFICATE-----

    MIIDTDCCAjSgAwIBAgIRAIjDgp4sTf072r8RbJS39AIwDQYJKoZIhvcNAQELBQAw

    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI2MDcxNTIxMzc0MVoXDTM2

    MDcxMjIxMzc0MVowGjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMIIBIjANBgkq

    hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvy3QHcTUd3TqKp1rr9g095G/gHBF736b

    HDNEWj7LuTHbRy5u7Bwh4OCCswF6NuFFIlFp9II80lgErIDfZT2eMcTj5r7Lhp3N

    yGYhUnvdKl4GeDu39zlApYm4DfimPLT25N0Fj6SG46oyhg/FNjsgKvT8xvz8oRXP

    pAjWUFqgGgSOVubQa6y83zoqO3gdp8FicqUiwtuarjZsgkqBdNlC7OktKkqKqivd

    pg/hf/3VTntchHhhTj5X7NvQQXMVLevs/2soXFVCceIGM7RwhSzKD4UyiaqoMnDM

    eb2GGMU11YLJt/1iquVKIgcfF6kv6faxtLqBhYD5kM9/5X1AK6RrlwIDAQABo4GM

    MIGJMA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH

    AwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU8lDey/1UXz+l1/9WeqzucW4/

    M2UwKAYDVR0RBCEwH4IdVmVsb2NpcmFwdG9yX2NhLnZlbG9jaWRleC5jb20wDQYJ

    KoZIhvcNAQELBQADggEBAESUoalqIifB4svlIjhtHDln3HN5S55XMffoM1q9dha5

    J75D2yHjbcPp55PoJIPCzY54ikK0iWaKaGj1+MM1IIzzcUf5Qt7jxUxwWnBfc0QT

    SkCMxXIx3ZSo+3A1IUQ+NRnFm52wRO3VdWtuYPjsfCtf4lmCj8PHZu2IhKRCUPGy

    iVW3XLzXufV0J+uMPeIxp9mmm+Ll0CoYMgsmulHzsTd91790G93BD8PEaq4RZgkG

    gSYDgZPKe5fIfmZfKD/ADqZylDdKnAW9dmQqOlgFYE1vAjPjZvu/XbNdxOWwJm7R

    NjXOh/30VhCcxkKAYJJJbA798JbLEvcy+deAV5YY7Wo=

    -----END CERTIFICATE-----

    '
  nonce: 15mCPi2/Kkg=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  level2_writeback_suffix: .bak
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/bin/velociraptor
  server_version:
    version: 0.76.6
    commit: 20c779e55
    build_time: '2026-06-03T10:53:44Z'
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
API:
  bind_address: 0.0.0.0
  bind_port: 8002
  bind_scheme: tcp
GUI:
  bind_address: 0.0.0.0
  bind_port: 8000
  gw_certificate: '-----BEGIN CERTIFICATE-----

    MIIDQjCCAiqgAwIBAgIRAKetFb3S4V1V/D9Bx/e2sggwDQYJKoZIhvcNAQELBQAw

    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI2MDcxNTIxMzc0MloXDTI3

    MDcxNTIxMzc0MlowKTEVMBMGA1UEChMMVmVsb2NpcmFwdG9yMRAwDgYDVQQDDAdH

    UlBDX0dXMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApjvoB5TCKpoP

    aMS1d1IyD7VXTmIXGXkPCVEKdNfayf7jDDyUGpSSS1NrTSVtc5Q5rK/biCC9jYfI

    OTmDLiwVzUcuXqrmM15S5X7E4ITZj+zQXpU3kK/NHfhtc2UYnZ+1LqeHWZ3mymXO

    e4gooOoavqmnqkJha5liPFUhzU+dpjGq3aqqV6jYk11MFSdeRaDAcRzSli/HE5//

    Dnfe7N+qMRq9LaKINlHrak4qyMf9UnciTLWE0CWKH9WtFYbgY8vifNUgrYNYzrJI

    XMhsjaRFvfwIeLNRkWcY61pZKuZg2OE4RncMQXs0KIT0yYfo50+K0QMq8I1DmWqN

    5ze0fV1R5QIDAQABo3QwcjAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYB

    BQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAU8lDey/1U

    Xz+l1/9WeqzucW4/M2UwEgYDVR0RBAswCYIHR1JQQ19HVzANBgkqhkiG9w0BAQsF

    AAOCAQEAHNjCZt14xip/dWJ7kH0VJu8ESVo5IQxTq6ckK5NVsJ+f6kmS2bzHytKD

    HQnoJma3zw2cb/EOBmh4mMWJOlhYShQCM/rnXrkgvnNt6rRpKd0p9GeW+fv3TQ1b

    VXZ5jKZO2ygA/FcCaP2h28CHf+N4R2+DA4Y3/YmTVyN0sIB0SzJnaHExVGwCCw0L

    XFAL/peXNhIJn3CoR5oJWR9lHuAOGuOQJgeu/1jLtohF2KHudjjWLf8y9A54Dxrx

    5ucO5CW9BqF+/YH1cdPwoUE0xvNYk42Ki9n4/6FLl7v3IujCpDXpkwV2cLC/tEQ7

    96QM7ncz3OLRQRXI63staABKlFimWA==

    -----END CERTIFICATE-----

    '
  gw_private_key: '-----BEGIN RSA PRIVATE KEY-----

    MIIEowIBAAKCAQEApjvoB5TCKpoPaMS1d1IyD7VXTmIXGXkPCVEKdNfayf7jDDyU

    GpSSS1NrTSVtc5Q5rK/biCC9jYfIOTmDLiwVzUcuXqrmM15S5X7E4ITZj+zQXpU3

    kK/NHfhtc2UYnZ+1LqeHWZ3mymXOe4gooOoavqmnqkJha5liPFUhzU+dpjGq3aqq

    V6jYk11MFSdeRaDAcRzSli/HE5//Dnfe7N+qMRq9LaKINlHrak4qyMf9UnciTLWE

    0CWKH9WtFYbgY8vifNUgrYNYzrJIXMhsjaRFvfwIeLNRkWcY61pZKuZg2OE4RncM

    QXs0KIT0yYfo50+K0QMq8I1DmWqN5ze0fV1R5QIDAQABAoIBACiZCdZMJM1tuaSv

    IdhlyRcgBRX+C8ErWRo/4gteKi9Z4g57fvos3buqwFJjeSMYiKtdeYJ56IE3r5UW

    MCznFF4Ba9gv6a+S8jDdMGza1R16yvrGe38JCFGw+d4MSyI3vnKJ9JrU3ugATBjM

    TIvcELMO0QVaV9uE5sJwUiSHtKtBIj1nmUkK5T6vhnxvC6Ohh1M8adI6kYQS5OzO

    lU0X8FrwlED6uS6DmaOaF8fzBpHT8HQYA/baugdXsLshfxatHzcJx19klbXSxGNh

    MKBnHwWPMDGsaJUFCED9rdGH/zYJE3gMs9eyJ+mSNznA0OaI7IBH+cXY8xfCf+nG

    MWzpW3MCgYEAybM6BDTi91rS0M3vLzoxSvYWMxF5UO1H2dyHgIEEIAcjP552kz8x

    zsaKLAhWFQfRbDRhr3q6rD9PIn4iHP/WNbXSyA0u1O04Ie2pWN57b0ff4U7xR4Qc

    PYzQ9qwlZGCkxKf8ZdlJQitsjq6CABDuWOZN6DSv4aBwgVlLNq2ioHMCgYEA0vxt

    KsiycR01w5Dly4AEQad2eMT6/G3pxGrIhE0tIOPbHPWkDpnI9qAjnsCHK/mD2rzn

    RQyhpEmpcr0KgLTlf4rYj95ZeMg0yV4iTLgYs1OZNb6LkN7oEgvOYUzYkPRAvv/H

    ZsAiBWDb5Rgq2rd3ER/0QRC0PODCdRcPF6UXZkcCgYAnE7Mkx35Ff/IiBBPX6YVN

    SZoJcNQ5Ko9mFQSnj9dVwSxCEhhU9MRYlDyGxWKwFmCrfwaB8dwirO1O+HLxfVtp

    8n0QxwUQuZjLcfkCP7BYYettAldajKzP++0sLTPdW5/wfb83mD5KNJGGnyaOjrku

    vgfP+g0tQGErnjolMMS2IwKBgFnV86Gw/RHezyKrUr04kBdod7BqpzfOkSf6E9EJ

    j3qeqpCFI0q4PnKMsz4IWkXmIzeDEbI786OhXc4mIg+1dra85wMzOMON87P+Kfqi

    tJm+sdDJhmG0F/p/HmwdrWTjK6JoBH6Ctrm1iUvd43lnfwJCqdz+gNAfH419uQZn

    XDRHAoGBAJIGRMlLY4mXZOY/BrWT1MNbawlbxMwUDeyqc/F1ERdVFYBqdY8ppj9b

    WYnQK3249EI+J/q7oiH9rdX+LO7/NCkE1w3IU9M4sNrryYfWGyrXNxBKrg0Q4R4O

    G/4TSSRwsYk3FM01RUbJkQGqqq4/CT4oWLcVol488Y+wVkICogTX

    -----END RSA PRIVATE KEY-----

    '
  public_url: https://203.0.113.9/velociraptor/app/index.html
  links:
  - text: Documentation
    url: https://docs.velociraptor.app/
    icon_url: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1MyIgaGVpZ2h0PSI2MyIgdmVyc2lvbj0iMS4xIiB2aWV3Qm94PSIwIDAgNTMgNjMiPjxwYXRoIGQ9Ik0yNyAzYy0zIDItMTMgOC0yMyAxMGw2IDMyYTEwMyAxMDMgMCAwIDAgMTcgMTZsNi01IDExLTExIDYtMzJDMzkgMTEgMzAgNSAyNyAzeiIgZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIi8+PHBhdGggZD0iTTI2IDBDMjMgMiAxMiA4IDAgMTBjMSA3IDUgMzIgNyAzNWExMTMgMTEzIDAgMCAwIDE5IDE4bDctNiAxMi0xMmMyLTMgNi0yOCA4LTM1QzQwIDggMjkgMiAyNiAwWm0wIDU1LTYtNC04LTktNS0yNnYtMWwyLTFjOC0xIDE2LTYgMTYtNmwxLTEgMSAxczggNSAxNyA2bDEgMXYxcy0zIDIzLTUgMjZsLTggOWMtMiAyLTQgNC02IDR6IiBmaWxsPSIjYWIwMDAwIiBmaWxsLW9wYWNpdHk9IjEiIGZpbGwtcnVsZT0iZXZlbm9kZCIvPjxwYXRoIGQ9Ik0zOSAxOWExMzQ3IDEzNDcgMCAwIDEtMTMgMjZoLTJMMTQgMTloM2wyIDEgMSAxdjFhMjUwIDI1MCAwIDAgMSA2IDE3IDUyODkgNTI4OSAwIDAgMCA5LTIwaDR6IiBmaWxsPSIjMDAwIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIHN0cm9rZT0iIzAwMCIgc3Ryb2tlLWRhc2hhcnJheT0ibm9uZSIgc3Ryb2tlLWxpbmVjYXA9ImJ1dHQiIHN0cm9rZS1saW5lam9pbj0ibWl0ZXIiIHN0cm9rZS13aWR0aD0iMSIvPjwvc3ZnPg==
    type: sidebar
    new_tab: true
  authenticator:
    type: Basic
  use_plain_http: true
  trusted_origins:
  - 203.0.113.9
  base_path: /velociraptor
CA:
  private_key: '-----BEGIN RSA PRIVATE KEY-----

    MIIEowIBAAKCAQEAvy3QHcTUd3TqKp1rr9g095G/gHBF736bHDNEWj7LuTHbRy5u

    7Bwh4OCCswF6NuFFIlFp9II80lgErIDfZT2eMcTj5r7Lhp3NyGYhUnvdKl4GeDu3

    9zlApYm4DfimPLT25N0Fj6SG46oyhg/FNjsgKvT8xvz8oRXPpAjWUFqgGgSOVubQ

    a6y83zoqO3gdp8FicqUiwtuarjZsgkqBdNlC7OktKkqKqivdpg/hf/3VTntchHhh

    Tj5X7NvQQXMVLevs/2soXFVCceIGM7RwhSzKD4UyiaqoMnDMeb2GGMU11YLJt/1i

    quVKIgcfF6kv6faxtLqBhYD5kM9/5X1AK6RrlwIDAQABAoIBAA0EI31DX2vaq+7G

    1QQd5k1MwQsPmdNafVkILIkwaVJskI9iG+87Yxsabgud+CIwaDKT9HDPRTDVCUxt

    YchUz6Z3z0RwjQ7XQ6F3QqGJCV/PEwWwmy/b2AjtPXjGCxtq/rxKSAylmQF7HwF9

    pWGx2NjT4TnzE4gsIfz7FQxXfzsGIjAALNNtN68LUGfx3JiKYqjXzsfwrwgkxhh6

    poHaFQJNb3IVoYTn2B9MSjwd1CxH8Y22TKYtDMfZpKT+4H8TXuzBFyK9BIb69eVR

    IEm2tUUOVpXUrYHRDSqtEzls/ufMulD0AiFoWuI0EbzD987AMfr3S3ZI9HX0220Y

    I3Lm79ECgYEA7UfrspraH6aeOCipl4Z3RU5fNtuJUehpd6trvCKRZLOU5P73nZj2

    cNAxOPvVId8qYjzCZ5HG2gzj2ZkEJOkJWmSU1vUvIlMqFGCIjFnnjsZ4qShfLawX

    /7CI6uvBn8zD9l+HiGkRLbVQk0AVyLTtgieSOLDtcgfFSXzqw6U2pLMCgYEAzkLT

    Xd4EHvwUk3Mtu5Q1nrwrx+M4o9WINZlwGSwmqCf6GvyPa5ojWdYwup93Dmw2IuuT

    4AFyY1EVp4+PjkcwBtYLrnjtBhKVsyhBQcESkmRENZrwox3lMYya90nq5YINw8If

    nZbxWtCaUmu7Epj66krgFZAMbgJdyJk/881R940CgYAu/6Di5qMvw7vxGbTFy5+S

    PbzES+W+MI+7YVvcjuhHjv5+ATago6ykmcg2JkOICwEFJk3HX+uIQydacWGNwg7V

    Nbj5fuUQInLiSGCjlCc2c39w2gtIK58xSRFFnt7iPRfPlApvbYg2ioRkNjxaXePx

    dM8UpY7SmFFuheymRfI12wKBgEnedvJkI9ew8fGIy3UldDqgK5HP16YdQEXp6NKr

    FEEe6ByoHPktX8G5ywPbPnlE2fKRqgkMm5nkHTxAVupepl2cZNycZE7Lcx+RqCVT

    b0JMdH06Ozo/56hiMdGkgGKnvCRCrq3ytAeRM+OWv42+igZEwJIYX8s6P7oq4FOB

    Ufy1AoGBAJtaLN1/HiqnWNtMNFUJE5gN4NqZwsyoRUoE8EZaZ2/LX+WTKQorSsCd

    FW5OK1B+U0bfyZj690DsG5K5lKFhgJ/hx8iwfNfT2fMGTVCZwu0viIztIX0OAldu

    YVIPkmN07sP4otD0vWn92RjXlt7c/olCoQjop9gOeywSsTbF8nwu

    -----END RSA PRIVATE KEY-----

    '
Frontend:
  hostname: 127.0.0.1
  bind_address: 0.0.0.0
  bind_port: 8001
  certificate: '-----BEGIN CERTIFICATE-----

    MIIDVzCCAj+gAwIBAgIQBvsQriGQBCXF69a16S18NjANBgkqhkiG9w0BAQsFADAa

    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjYwNzE1MjEzNzQyWhcNMjcw

    NzE1MjEzNzQyWjA0MRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxGzAZBgNVBAMTElZl

    bG9jaXJhcHRvclNlcnZlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB

    AKY2V9xMi8hMDdSyzkdS9TPU+vDT9JzKOKiVS0MtTYfpHz5B7fc09D8QfrkWcLBu

    1hEsUyLFwwE9YwdzZuGpwujxHxmAfPI+63UvthOkaDRHRYAnjIfrb6Ek5g0DXcKu

    6/tn+FgH6ahmt4gYoSHsas0GNdJFGVj81SguK2pqP2WjgIfqdYF+rsRHkb8z0/HF

    9UB9JCjyyo2kjWD1SU/809MtJ23NBF4blIWHgvxJP3l0QDKN1qGsxodqcoD3oPVL

    NMc+y+X+yiTdHoVL6tejZWWTGTk57eyXkoHit4L1gw4ekSAjr0QA6/bKB37KVOrZ

    Q8OumyYnbhKMMyvaisvrTqcCAwEAAaN/MH0wDgYDVR0PAQH/BAQDAgWgMB0GA1Ud

    JQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB8GA1UdIwQY

    MBaAFPJQ3sv9VF8/pdf/Vnqs7nFuPzNlMB0GA1UdEQQWMBSCElZlbG9jaXJhcHRv

    clNlcnZlcjANBgkqhkiG9w0BAQsFAAOCAQEAGEm9gusXMqdpvQx8t395c7DPiBUC

    HbA3zsFbrHWRc9CG30LedGsemWG4LEmEBdlUXsHSx8VDAXWd1sogJQEzLvZuJJKk

    66cPT/E0dNgPl8N/XpppqjDh2wahtfstEObqy59c9rH3/BCcZK2YIcYy9iIgehHG

    6UW+1uHtlK3W+6YiXg34sz99qabLOPCcUbohTda2Ax5DLigA+IYHh2P9rIIqd8od

    BYn6lZgyJCTkZQsIG8y2SD4fWuP7SeznmTol7ZAL+1b6tFfEmJ4TOkFANE6S7VWF

    qHkOem2WZsSvLtOHtLTyoFxwgNx8tksIAEvYGMYF4F9hCC4cgyXwmoJdRg==

    -----END CERTIFICATE-----

    '
  private_key: '-----BEGIN RSA PRIVATE KEY-----

    MIIEogIBAAKCAQEApjZX3EyLyEwN1LLOR1L1M9T68NP0nMo4qJVLQy1Nh+kfPkHt

    9zT0PxB+uRZwsG7WESxTIsXDAT1jB3Nm4anC6PEfGYB88j7rdS+2E6RoNEdFgCeM

    h+tvoSTmDQNdwq7r+2f4WAfpqGa3iBihIexqzQY10kUZWPzVKC4ramo/ZaOAh+p1

    gX6uxEeRvzPT8cX1QH0kKPLKjaSNYPVJT/zT0y0nbc0EXhuUhYeC/Ek/eXRAMo3W

    oazGh2pygPeg9Us0xz7L5f7KJN0ehUvq16NlZZMZOTnt7JeSgeK3gvWDDh6RICOv

    RADr9soHfspU6tlDw66bJiduEowzK9qKy+tOpwIDAQABAoIBAAWu/AgjcfAycZKh

    Xp5fvtS75qzPgqDN5WwWVtGAPhN0rEXTuVBntiZl6P9pPgc6cwV5T4pz2rwzHizG

    DHGQ/YI7pIWZuCwMbL7AF+jKCWooOb8tGwgWy+VlvpwZTl523sjlAD/6XUoN4R69

    QN1JGUnTeYmsJTa+xocuNPvZkDtocsHFDPCe3o7cVn5Egs82HBafZkdGmDXadI+o

    vwyfFq5buhraLsIL0QjsdIhucQWS/7NuqbClYPdfs8EfcvUj/RLjrYsB9iuZHkXG

    TGoXzd6cQZa+CweJ3hyStEQbF3SSrRcrhl/IsEPVF9/BrGfqQS3KWKM1EJV6GZRv

    Z5X0KHECgYEA1gpDtyd1qBIFL4+Tpe/drsOcldQZVOfVb9XKXzvzRjpnNrVw14eR

    dJJSVzTnVeEj/IRbb1p7jxGDFQPteHgRgM5ER3E06Kt40no6tibtcgpswDBesm3M

    7TxbRBQydXma2LRCRyI8vhLMlKCW7glZwUwz1EG0UggsPX3GX1/kyIkCgYEAxsvP

    VH5iORrLxHkUAUJYTiwOt9Xy/htlDuiTljAfkNvISUzVFHrbkJ15xh912g6oiVB7

    nSlef3Tp3RvNfYbTx/pDdsixh0dwMTXXCev5PTfzfZcBpC6cTmcimZvYAhSrvbGb

    jBSfRp65Dj6NZniOHvaQFwWcmcBFyx+hP0IEMa8CgYAtt3eLMURyJ5cv92zD7p3c

    7C8P2YOnnPT7tCBLgxSNFYBiMRLvFie9TFuGAOjAcRwsnWCiQiNOBaGH5ZTdPFgQ

    uP3gfI+eerGN00mjCmGBEDT2P96aIdW5fkDII8A7U0P9sVLOusNanc1QmZRjN2AS

    Z2JSnc4UD2bTo3+xc1v8cQKBgCzytCQkl0zWFDCON8m5GIJET+edBl4SD515VLVm

    mByGtRhtuNfyl2ZxVLFJN7pgChdSDUERs34aDy6hNKsnKwdSPKLE6e7uZh2aUM67

    fhUra3CADizzJQBNLXOR2xtNVS+E0uivWPv8s1bXKd17cJbrpNSvviK9aIpu0mSd

    JpmdAoGAd7iu3l/g+KEaQk+2rhVAFbvuFvkhEKAe2q8AHdxsBDOLbiSaNNuvwQ0b

    WDg5LJEiIdoE4GmmSyAX5X61qx/5eMeiM6Izr8pH5GKICA1WoV4H5IxyhKI6679+

    8PF2rdQi9kvL8KdesAs16S2Qlkx4V5ChMfLCvoGwAsq2kmCOiHQ=

    -----END RSA PRIVATE KEY-----

    '
  dyn_dns: {}
  default_client_monitoring_artifacts:
  - Generic.Client.Stats
  GRPC_pool_max_size: 100
  GRPC_pool_max_wait: 60
  resources:
    connections_per_second: 100
    notifications_per_second: 30
    max_upload_size: 104857600
    expected_clients: 30000
  use_plain_http: true
  base_path: /velociraptor
Datastore:
  implementation: FileBaseDataStore
  location: /data
  filestore_directory: /data
  compression: zlib
Logging:
  separate_logs_per_component: true
  debug:
    disabled: true
  info:
    rotation_time: 604800
    max_age: 31536000
  error:
    rotation_time: 604800
    max_age: 31536000
Monitoring:
  bind_address: 127.0.0.1
  bind_port: 8003
api_config: {}
obfuscation_nonce: CubvoUr3mxA=
defaults:
  hunt_expiry_hours: 168
  notebook_cell_timeout_min: 10
security: {}
