version:
  name: velociraptor
  version: 0.76.6
  commit: 20c779e55
  build_time: '2026-06-03T10:53:44Z'
  compiler: go1.25.3
  system: linux
  architecture: amd64
Client:
  server_urls:
  - https://203.0.113.10/velociraptor/
  ca_certificate: '-----BEGIN CERTIFICATE-----

    MIIDSzCCAjOgAwIBAgIQY1SsP80FcpewmCe6z9kBijANBgkqhkiG9w0BAQsFADAa

    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjYwNzIwMDk0NjU3WhcNMzYw

    NzE3MDk0NjU3WjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG

    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDMZKMqKoLI+8H5MDMAkiXH8nbytJ9iEQgD

    CebvTcJTyCFb6UP0xhJA+UJ12TAVHfY00BSwncVbq0CsEnMue8ULSPyipUjevv0H

    TIYhUXt+yBWnvhH90gTnk3zp4vWNfHbDL/mgWO/kD5N1eto8ov4A8MbSh65TtnIW

    vq0U8OiU6/Uu4ssWWVnsN8U/vPFX1jSldSRR1ESUVfOGccHsFB3tUQnH08Zc50xU

    m/mCINz73YUTGiHhtgYktAxzw1iXuxPetLbShpZtO4S7HxxanFubOHZnXIiFZyo8

    w1VwJ2ttY2rXdLzqpVHVfganufVTHTD4kTTRfPf/eXGBqAfWKheVAgMBAAGjgYww

    gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD

    AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBS1ErCsykiLcG5a7xcT8ie3maSv

    5DAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq

    hkiG9w0BAQsFAAOCAQEAavboEYkyXxhkYgY4mNyVwBnNPgdBFRdZUo66qc1q1oAP

    YawiqiSRJI1OLo8h27+/Df+PvtSQeROvVTykU/dpwFOHPAOK35ytLrufsjnLSBTo

    SwDAt748WFbq3wk+EqTwXtY2e/zjA7t58OQ82iHvsJnY3TmC0RD7QlSf6aU2Nw0/

    7zlACPDXNGz0JbtVdcG2KX+nCN2WeEwUzLS1v88eQ0dRvqt5Ey0GV6lS5E6I51TU

    oFJe9blqM+7K+PGOvCpmOu7+UMMWQxR0GQqUd+EgWhW/Qz8UIi7JAjZuTg+GY+Uh

    Ul03xEuzxPfFurIZdcdb/VAwCKmYRcibeZJX3boKLQ==

    -----END CERTIFICATE-----

    '
  nonce: rZdmaWYvhcM=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  level2_writeback_suffix: .bak
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/bin/velociraptor
  server_version:
    version: 0.76.6
    commit: 20c779e55
    build_time: '2026-06-03T10:53:44Z'
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
API:
  bind_address: 0.0.0.0
  bind_port: 8002
  bind_scheme: tcp
GUI:
  bind_address: 0.0.0.0
  bind_port: 8000
  gw_certificate: '-----BEGIN CERTIFICATE-----

    MIIDQTCCAimgAwIBAgIQec1lGLXyzGP9QcdX4fF9sjANBgkqhkiG9w0BAQsFADAa

    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjYwNzIwMDk0NjU4WhcNMjcw

    NzIwMDk0NjU4WjApMRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxEDAOBgNVBAMMB0dS

    UENfR1cwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDC+5eqCdTOBwyQ

    4GAKFRETqxpcBPzOVCZYuguIbIkKZL1SkoeOqBwHI4Zr6qN2imu85VcTtCNf3RAF

    3LSYXynuUFsd8oEnl7QYqTINKATgZVXEsDwIsC5yxLYKW2Xao0aZ733X2GgU9z88

    BqJsPQVzVb5VNeGwYQ+vixvqLvcIUUJ5o61l9SGtzyKAkqLqKfusvGu02dNoPKy1

    rqkyOjPZrvQOKg/YnXCcevV75tBCV7Lpe1xAj17cJPzt1KDtzkL5R3bXWYw+rJJb

    GKgQKdGIr/MfraLv7fgQZkTs9RwyJsatU/6t4eFGUHm1KJB8WSET9JGMgfyJbC9l

    cTkHeQEbAgMBAAGjdDByMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEF

    BQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBS1ErCsykiL

    cG5a7xcT8ie3maSv5DASBgNVHREECzAJggdHUlBDX0dXMA0GCSqGSIb3DQEBCwUA

    A4IBAQBxvTy99MO+BaDhUit7etK7+xtUd46MMgu9DAvTnb9ChsxgcZwhkqrkF+bc

    jUSO16SRMNDwtaiLK0GoCy64+F0YvruFPh4xD9U+/vk+tGKubRnTl+aV7FXX15T1

    FKIpn2EXuOjcM6hsqrTKsXNbfQWIZ+8KTCI+ZsAsyaiZZICmHlFFtrKD5SF6glK6

    WviUHqI7N3hMOZTvD6bsFFiYRW6I4et1gqKziDJc52K2rJOsexWQjmsO35mJDW4H

    YX9Wed29NqViHvfHxDSJ0YSKJfNJhvHHtswntOPKZmaSbpjcBBngd/S7o5V//bHE

    0dUhjdh9OlA4vQEGkQApX3PCD29w

    -----END CERTIFICATE-----

    '
  gw_private_key: '-----BEGIN RSA PRIVATE KEY-----

    MIIEogIBAAKCAQEAwvuXqgnUzgcMkOBgChURE6saXAT8zlQmWLoLiGyJCmS9UpKH

    jqgcByOGa+qjdoprvOVXE7QjX90QBdy0mF8p7lBbHfKBJ5e0GKkyDSgE4GVVxLA8

    CLAucsS2Cltl2qNGme9919hoFPc/PAaibD0Fc1W+VTXhsGEPr4sb6i73CFFCeaOt

    ZfUhrc8igJKi6in7rLxrtNnTaDysta6pMjoz2a70DioP2J1wnHr1e+bQQley6Xtc

    QI9e3CT87dSg7c5C+Ud211mMPqySWxioECnRiK/zH62i7+34EGZE7PUcMibGrVP+

    reHhRlB5tSiQfFkhE/SRjIH8iWwvZXE5B3kBGwIDAQABAoIBAFy9E5bRlEDmA2kI

    /0TsXjHvqNrpmGB+j7qVypR5ovipj46tmQIWHTacA/xiHptsHPA8WJ1LiaO33j4b

    il4KrUPnPl9RD3MIaaVtHBw7043zRMcHV5Z+TalSvI7Sh/BkxljDGyTFjkOikZX4

    Rdqbb3M67gtTVGPy1mYVERLigaaXQhZre7fsA5grGNAAppjE3S8d/bivW9iumMMS

    qcW+vEs1FHt+oTv+s52pF3Nc1NqeTREKRAaqPCtBh+s/Z675z4U9KdKWq+cTFFd1

    Kc7d7gX7to/IS2OtpqrXJpPgkeiWZb4aXgX//xfGcMK4c6p60fcYy8R3GOhSOoHb

    /ecvrwkCgYEAybqdCSOpNq74AokMfgaHnVgZ3aqpYdo59UpFzbjOKRtbjjm7/4PY

    qBjnIJ9CeI0eJcDnd2QS+vf3zUrJi82HMFv52RdnjqnAgv1bB2LU6zLoLUhRSdu9

    zen9/O9MPvIHE3DL36muAcDplCDG3QycT0hcHYuRE2Lz+hI9egmu9vUCgYEA93Bc

    AxzwW5t8IKwghc33F3qxBNLZ2iCjOzRKTp9BCiT3PrMRm1O1sxmvPI+JyfoBYwyD

    EMRrnOZ4Z8PEu4nEORDzHolAn6u+2oM8bjWbr7qo7e6QHqt/7q+DP50VpOB1hVKw

    WKJW1YcuAsQ2BbRLMTpv2bEjhd732CA4rxLVbc8CgYBpVd1cAVgBatmsET4JrIUx

    3ugavFuX8eijsbXDV0WnZ1ambHVDVehS1jYR7bc61Y0xb4ot6H6Ut9iYRP3610ZJ

    NS3Acx0q/G6+t2bJ84x0h+9+fa2coHZ6yD1MzvOERsL1HsgGMUbgOYh+RaMxl70j

    FQiskM0fT2NQaCfbyqSm5QKBgHvvwYalphacaK4MyTV8Frmh8KyT2B6Tnm73IAkF

    Z5RnM5gqJTWB1k7hHI7e7otGOA+eor9xQt2R6tk+i3nL5YcX4E55PO89HRliBpDF

    NTft7NNQXMuf5zJsovbn/YFaFEM1SbL7jTbiwL8N/GkbB1afCIsnWL2jEs0kRoAa

    lOCtAoGAK2LpXWfl5sE5a/qcZ/Cc0fWjwoS37TqGDUlU66TTZ+coSQu3QfFwPkb5

    5Z2x8g47wjNY2ylzQsjZinQB3AhSOSksXyrNORAQauzwhlew/BlCAdX9rraP7BYO

    8KwEyNb6b0Q26XY2IAt/rgdTmcEbvt0nwPHabwed18+Qv4yl9i0=

    -----END RSA PRIVATE KEY-----

    '
  public_url: https://203.0.113.10/velociraptor/app/index.html
  links:
  - text: Documentation
    url: https://docs.velociraptor.app/
    icon_url: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1MyIgaGVpZ2h0PSI2MyIgdmVyc2lvbj0iMS4xIiB2aWV3Qm94PSIwIDAgNTMgNjMiPjxwYXRoIGQ9Ik0yNyAzYy0zIDItMTMgOC0yMyAxMGw2IDMyYTEwMyAxMDMgMCAwIDAgMTcgMTZsNi01IDExLTExIDYtMzJDMzkgMTEgMzAgNSAyNyAzeiIgZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIi8+PHBhdGggZD0iTTI2IDBDMjMgMiAxMiA4IDAgMTBjMSA3IDUgMzIgNyAzNWExMTMgMTEzIDAgMCAwIDE5IDE4bDctNiAxMi0xMmMyLTMgNi0yOCA4LTM1QzQwIDggMjkgMiAyNiAwWm0wIDU1LTYtNC04LTktNS0yNnYtMWwyLTFjOC0xIDE2LTYgMTYtNmwxLTEgMSAxczggNSAxNyA2bDEgMXYxcy0zIDIzLTUgMjZsLTggOWMtMiAyLTQgNC02IDR6IiBmaWxsPSIjYWIwMDAwIiBmaWxsLW9wYWNpdHk9IjEiIGZpbGwtcnVsZT0iZXZlbm9kZCIvPjxwYXRoIGQ9Ik0zOSAxOWExMzQ3IDEzNDcgMCAwIDEtMTMgMjZoLTJMMTQgMTloM2wyIDEgMSAxdjFhMjUwIDI1MCAwIDAgMSA2IDE3IDUyODkgNTI4OSAwIDAgMCA5LTIwaDR6IiBmaWxsPSIjMDAwIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIHN0cm9rZT0iIzAwMCIgc3Ryb2tlLWRhc2hhcnJheT0ibm9uZSIgc3Ryb2tlLWxpbmVjYXA9ImJ1dHQiIHN0cm9rZS1saW5lam9pbj0ibWl0ZXIiIHN0cm9rZS13aWR0aD0iMSIvPjwvc3ZnPg==
    type: sidebar
    new_tab: true
  authenticator:
    type: Basic
  use_plain_http: true
  trusted_origins:
  - 203.0.113.10
  base_path: /velociraptor
CA:
  private_key: '-----BEGIN RSA PRIVATE KEY-----

    MIIEpAIBAAKCAQEAzGSjKiqCyPvB+TAzAJIlx/J28rSfYhEIAwnm703CU8ghW+lD

    9MYSQPlCddkwFR32NNAUsJ3FW6tArBJzLnvFC0j8oqVI3r79B0yGIVF7fsgVp74R

    /dIE55N86eL1jXx2wy/5oFjv5A+TdXraPKL+APDG0oeuU7ZyFr6tFPDolOv1LuLL

    FllZ7DfFP7zxV9Y0pXUkUdRElFXzhnHB7BQd7VEJx9PGXOdMVJv5giDc+92FExoh

    4bYGJLQMc8NYl7sT3rS20oaWbTuEux8cWpxbmzh2Z1yIhWcqPMNVcCdrbWNq13S8

    6qVR1X4Gp7n1Ux0w+JE00Xz3/3lxgagH1ioXlQIDAQABAoIBACNH4dRG90FbF638

    UGlyULw1UavuWq6yUug3XtoC2Z7dpkh3uOe5AvCdNggin8adX+DY5CFicm0y39xz

    6NbmvWoHxLgMgMoWPJX0cxiwOHl3byl/yRo/lOImVsMGjq1IBTYHA3dWsr3ypFj8

    hkw+NEsURLWVfxVrIkFj03uQZA1EaGruvaz4MoEBBifpMVT57meC1LUIr+z6yx/7

    q6UNauTUloEJv71H7QCwFFA5kaLcpq2tDGwzo8Rw3GXT4VVeb9/AiDby4p3OvhtY

    2MOdT9fj+b2RTuasceRQ//MA8tzQjm1NV/gQgOnVIIUM/N6s7oretgWxOThK0whi

    UbJHQ/cCgYEA9SAcPpK4Qr+CD2ryiMZMuspoLJqSuIn0qlk/Ltei979H7iKro73I

    1N/Of6xmBwDW36GiLKDay+7/NGejzPT4+u+USRn6zqrKF2U2FQcYUYpjyzUQA/Si

    7NDDrZrCXDs085lPDPl+zgZEft1ic8GuJ0o6ph6kWrDs1nAnEAaXMZsCgYEA1XXu

    Gndjr2DcEHFKa4Gtycv/Ghf3j0i+Lc+SPUBMFSr7IGIcM/pb1/hNgRHNqsJX0Y19

    kWekeaaUxRFmp/ONSQHDtB9rQn/YvtuHeAj1xx9C6DG4ghOdocd+V7w1xwA6XRX8

    BQVcCPHKd2+ypkrpj+cts6H4VQnA6EEHoAE/Ro8CgYEAhCS1VT4/OyyGbs1Wxkkw

    oBnxouoJYpZsYVEPcK8q2agynLvwD6uGEsw8RDOqJOhc7d3y0WA902aaCaQ9d4Yw

    mwaAyA/LV5JWs9oKF7flcj/KoIeQhLFjC4tXkcU2NgZs+02QggwWQfa7AjFSm9iz

    i9bGWzt1mrZ6VvfK9ya2ZzUCgYBfx0CFA5jo8k8L2amIv3EZIL1gGezsj7k1mPOH

    JDh/Lv/rMdpxwB5Bs5ojFbfwrK72ycPT4Gs+Ym5SVlJ3faKhZXdIdOiNuAuq55nL

    VEnjhLVithyR0Pdjxb185GhE2GdXqSuhnRwEr2knWikQ0IAoH5S0CzMABRZXoAYp

    1yVrJQKBgQDS60fIQDF0fJCSaJoVeHjkgwCGECy2kABILqmGN6ESiwInDs09YHlf

    6xP3Ez8p8WYYbOWMtwEE3OKpiIR2wxHjnOb4hvS5LtD2gFSGKCOIdz4S20fUeuQh

    2qgdkogabDVaCqviDsG7+yWrxxV2sZdyf3/vE/FCDsSnix+jWA4pqA==

    -----END RSA PRIVATE KEY-----

    '
Frontend:
  hostname: 127.0.0.1
  bind_address: 0.0.0.0
  bind_port: 8001
  certificate: '-----BEGIN CERTIFICATE-----

    MIIDVzCCAj+gAwIBAgIQd/bM+LheVPymkGrp9haYdzANBgkqhkiG9w0BAQsFADAa

    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjYwNzIwMDk0NjU4WhcNMjcw

    NzIwMDk0NjU4WjA0MRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxGzAZBgNVBAMTElZl

    bG9jaXJhcHRvclNlcnZlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB

    AOFwCfIiRZ27hYNQ+/9PLaHcMyV/IlknqJEKqRy2eToNaU2cQ4XWblMjyfvyOEsa

    P42+lq0uk6qLqJCUyQPkamh5t3NLaRecj3CuIjl0O+AKEwqF+ND7smykv99t493X

    Xo0nJFhdlGiqDO8ubhxbGCkOkI5lCkE3T9eJ7Vl4BfL2FFu2PDKbxI4NLEnFLBYC

    ZYgLqV0VtNyo1mhpzv5baT2jTfuxLfxnLStZp5HRJKwkh5U2Et6d1czIza97b62O

    WExCCnQ8SQbTfizpHyY2juqgfszZj+fbFYA5UaBXCOmdKcS6xb1UNHLnwF/d/gwz

    cMMm3VcpUl/glijTKfTwf2cCAwEAAaN/MH0wDgYDVR0PAQH/BAQDAgWgMB0GA1Ud

    JQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB8GA1UdIwQY

    MBaAFLUSsKzKSItwblrvFxPyJ7eZpK/kMB0GA1UdEQQWMBSCElZlbG9jaXJhcHRv

    clNlcnZlcjANBgkqhkiG9w0BAQsFAAOCAQEAV1MsJwrBwhSm4GYqAL+q3S7QlZ6J

    /qD8VVSrCWIw/qDso5iF0gpw0sxQrgY5XgBFYP0V3mWyRDn/rKpHph9+L1fSDEA+

    AvOprWgGIPMww3bDk1tSnIkyoB4XAK88XmI7nYKR6JJaIXCCSRNGyDpvJR3qYwgd

    vQCjfRdQy6IP9O95eGfRpPD5kXBllUXAyznSdG8ukbe54FCQGernF48fzH288Za2

    kfo3YY7X3IuTuJAN1MJ+TWd2EopWi/e3CNGZBVJDMBT41qpsOkIAR2hn6njO4HoQ

    g/QZebd5xGM9UTe1gqIjPqR/cpJKtpQuzK15oSKp28qETLxjXvohVYKlgw==

    -----END CERTIFICATE-----

    '
  private_key: '-----BEGIN RSA PRIVATE KEY-----

    MIIEpAIBAAKCAQEA4XAJ8iJFnbuFg1D7/08todwzJX8iWSeokQqpHLZ5Og1pTZxD

    hdZuUyPJ+/I4Sxo/jb6WrS6TqouokJTJA+RqaHm3c0tpF5yPcK4iOXQ74AoTCoX4

    0PuybKS/323j3ddejSckWF2UaKoM7y5uHFsYKQ6QjmUKQTdP14ntWXgF8vYUW7Y8

    MpvEjg0sScUsFgJliAupXRW03KjWaGnO/ltpPaNN+7Et/GctK1mnkdEkrCSHlTYS

    3p3VzMjNr3tvrY5YTEIKdDxJBtN+LOkfJjaO6qB+zNmP59sVgDlRoFcI6Z0pxLrF

    vVQ0cufAX93+DDNwwybdVylSX+CWKNMp9PB/ZwIDAQABAoIBAAl9lP2bkcC1L0a6

    9xDlfW9N/N08P+7u63rHrxzlVa8q917sEC+nOlfHru4rYVFQFpLaDi/WQSMx4/PK

    P7gpOo2RajaxWwhCcAt3WTt/+DFTWz/bKgFqRzWpreYzEx+4vGNG3ZHWxrOtTQQY

    uUv6TccUtOM5v7fFI1hYlyRoGCAFRdNHtnzSTRq/BMmbv5W5uD+56wzx6UIsq7Cx

    RMPn1kSiEuCWJd1fpc+L2B9zSD1csUa0I9h7oJgyvqHWiAVpmhMzrGrUdYa/MEyJ

    tk25nv67MErX7BobPg5xLtY44klimsVRI9OqFIcaYleZ3l0xoSrjVddcv1eSFkOV

    rA5pcwkCgYEA+B6JsdkqHbQnwkbJevi1cxtIfq9fkAFbZ8Wm+RxD4jlE1Vs1qgIk

    ykmrcAMZsSCKWUo5rTz1j4WT5oyZqCay8lMVZ9w6UEQzqlkdk/wf25rvzH3wt4Ln

    uQD6y2y0Gb7QAmMZLhG1bhutPDDtBkXAt2muQ6W0dtLPF+aLtmz41z0CgYEA6JkT

    gmmziZ5oeRPp29hslvzwMHGuhDvmiy45YAb3IOhQyLvaNZ3jcqMsh/oIq0AsKzG1

    jKMZGLxdjzZx5BxHiwN/QEkOpogaHeWb9V1/8nd6mXAzRAZeVHQuKvRJ53Ddp85i

    2t3TpUqeIOcC+MpAxV0izBrO44BREVtuLUiL+3MCgYEA9fkANGm/kNbqm3SlhN1O

    tKAVjFG7gP13ajbNwyO8QGbZ0FGtr66UXl4OMOtB6xEBVmd5Kj7GidO4vdQg+Ev1

    Fro6/E2dGbmjJntWEUDfLEw68hTgMGz737IS7twC54r8l4E6kytHG7MgWA2AzLkV

    xj5kXffGIg329BC/7Me3IVkCgYBW/DBEnD0NYVVWunDBy91IVg2JQGpwf2pHcKD6

    XYB8KQVVHJONa5+M1qMnswUc7iHWgX+Qucn/6yneDhFnqn/C6Crloqy88Lc7qQu7

    Jh1cUvxhd4lkjjEmylAdtkARMq9iOxfTHBQzg4VBbsM4wYKZjKwfwoLOp8UphZTd

    kHzxKwKBgQDtSZ24YBPi95aE22EH7EbsLWHzL3YOCn0SB8MfA/tJQJ7KA9sQU7/J

    v8828WyORu9k9DkxPsRvujxYmMnAHSw4rYTST7MLRcpT1Oj7WBPFSeJvoPR8RZvo

    eBUkFZSKcYPPc9N/+cx0JYQ2BYkfumzxDWVlIv7H5bvEWRMqe7wVaA==

    -----END RSA PRIVATE KEY-----

    '
  dyn_dns: {}
  default_client_monitoring_artifacts:
  - Generic.Client.Stats
  GRPC_pool_max_size: 100
  GRPC_pool_max_wait: 60
  resources:
    connections_per_second: 100
    notifications_per_second: 30
    max_upload_size: 104857600
    expected_clients: 30000
  use_plain_http: true
  base_path: /velociraptor
Datastore:
  implementation: FileBaseDataStore
  location: /data
  filestore_directory: /data
  compression: zlib
Logging:
  separate_logs_per_component: true
  debug:
    disabled: true
  info:
    rotation_time: 604800
    max_age: 31536000
  error:
    rotation_time: 604800
    max_age: 31536000
Monitoring:
  bind_address: 127.0.0.1
  bind_port: 8003
api_config: {}
obfuscation_nonce: Ijiaxi9Ewqk=
defaults:
  hunt_expiry_hours: 168
  notebook_cell_timeout_min: 10
security: {}
