version:
  name: velociraptor
  version: 0.76.6
  commit: 20c779e55
  build_time: "2026-06-03T10:53:44Z"
  compiler: go1.25.3
  system: linux
  architecture: amd64
Client:
  server_urls:
  - https://192.0.2.67/velociraptor/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIQfJwEaV76fSGOmY7pDdcP9TANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjYwNzE3MDE0MjM3WhcNMzYw
    NzE0MDE0MjM3WjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQD0dqSerkrPIVcQQ2kQ6BubpiJEi5A0gLnV
    u2bt5WQkWL1exTd5nwLvITwpJYOn7CLd37xmpLGEJhf8zh9cfqw3tPMiobr7VBzk
    TMqfW4hKWtnEXu7OlsAtm8gHazS/9dOHB9fYgpaL0xY2P3XWMNCFYk366LaCermL
    U6IuIkDfuRtgbTeXK0npHThpk5zvuQ69eCxYJ1ZvTpAP6T0+vV3vT+HU1YH0wXfM
    1AJkYrpqG2n1t+puzMG4X+6n29OvNJZ4V1mKwKButlMgPyWXOFMdw0y7z8LjN4mn
    IBU/au1iqQhvfls7U+jkql9K4uqFxoK/nI9m2HJskUL4J9B1titRAgMBAAGjgYww
    gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
    AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRsz1pLterGgCwJUKbZsafe/qXR
    STAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
    hkiG9w0BAQsFAAOCAQEAZ0lmAcOjQEriqmWe5fRHkespkr3FcJZne4V2Ug70k4NV
    qFSfXdiHN8/NJysP2iDaM+vil+qMZt5CU4NHPMHHZSmuXToxqiS7aQhHAgDSX/ko
    Qauklv9sxL2oO3mkG7i5N9kxB7TFJVN+RJp65ljz4chGpOqHl6axL1eZVKrLUGVd
    To2PfFqof/Lleyx1rlfnCjZOe6BCdYnsiWnPTTw0S0O+hsvcW5uvbIVHTS6H6hP9
    +/zhbYnOCHKGgEpczmEmhILHXrptg3ka0r+ZSo3fafkgUWgblJU+MQ57ckXuF+9q
    vB2sKp1nGTcQZ8y5LKCgxUf/ohC1n+Tgx+DWze+7yw==
    -----END CERTIFICATE-----
  nonce: 201Vuc9jojI=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  level2_writeback_suffix: .bak
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/bin/velociraptor
  version:
    name: velociraptor
    version: 0.76.6
    commit: 20c779e55
    build_time: "2026-06-03T10:53:44Z"
    compiler: go1.25.3
    system: linux
    architecture: amd64
  server_version:
    version: 0.76.6
    commit: 20c779e55
    build_time: "2026-06-03T10:53:44Z"
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
