version:
  name: velociraptor
  version: 0.76.6
  commit: 20c779e55
  build_time: "2026-06-03T10:53:44Z"
  compiler: go1.25.3
  system: linux
  architecture: amd64
Client:
  server_urls:
  - https://203.0.113.10/velociraptor/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIQY1SsP80FcpewmCe6z9kBijANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjYwNzIwMDk0NjU3WhcNMzYw
    NzE3MDk0NjU3WjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDMZKMqKoLI+8H5MDMAkiXH8nbytJ9iEQgD
    CebvTcJTyCFb6UP0xhJA+UJ12TAVHfY00BSwncVbq0CsEnMue8ULSPyipUjevv0H
    TIYhUXt+yBWnvhH90gTnk3zp4vWNfHbDL/mgWO/kD5N1eto8ov4A8MbSh65TtnIW
    vq0U8OiU6/Uu4ssWWVnsN8U/vPFX1jSldSRR1ESUVfOGccHsFB3tUQnH08Zc50xU
    m/mCINz73YUTGiHhtgYktAxzw1iXuxPetLbShpZtO4S7HxxanFubOHZnXIiFZyo8
    w1VwJ2ttY2rXdLzqpVHVfganufVTHTD4kTTRfPf/eXGBqAfWKheVAgMBAAGjgYww
    gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
    AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBS1ErCsykiLcG5a7xcT8ie3maSv
    5DAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
    hkiG9w0BAQsFAAOCAQEAavboEYkyXxhkYgY4mNyVwBnNPgdBFRdZUo66qc1q1oAP
    YawiqiSRJI1OLo8h27+/Df+PvtSQeROvVTykU/dpwFOHPAOK35ytLrufsjnLSBTo
    SwDAt748WFbq3wk+EqTwXtY2e/zjA7t58OQ82iHvsJnY3TmC0RD7QlSf6aU2Nw0/
    7zlACPDXNGz0JbtVdcG2KX+nCN2WeEwUzLS1v88eQ0dRvqt5Ey0GV6lS5E6I51TU
    oFJe9blqM+7K+PGOvCpmOu7+UMMWQxR0GQqUd+EgWhW/Qz8UIi7JAjZuTg+GY+Uh
    Ul03xEuzxPfFurIZdcdb/VAwCKmYRcibeZJX3boKLQ==
    -----END CERTIFICATE-----
  nonce: rZdmaWYvhcM=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  level2_writeback_suffix: .bak
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/bin/velociraptor
  version:
    name: velociraptor
    version: 0.76.6
    commit: 20c779e55
    build_time: "2026-06-03T10:53:44Z"
    compiler: go1.25.3
    system: linux
    architecture: amd64
  server_version:
    version: 0.76.6
    commit: 20c779e55
    build_time: "2026-06-03T10:53:44Z"
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
