global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: grafana
    metrics_path: /metrics
    static_configs:
      - targets: ["forensic-grafana:3000"]
  - job_name: loki
    static_configs:
      - targets: ["loki:3100"]
    metrics_path: /metrics
