filter {
  if "syslog" in [tags] or "linux" in [tags] or [@metadata][pipeline] == "linux" {

    if [message] =~ /^<\d+>/ {
      grok {
        match => { "message" => "<%{POSINT}>%{SYSLOGTIMESTAMP:syslog_ts} %{SYSLOGHOST:[host][name]} %{PROG:[process][name]}(?:\[%{POSINT:[process][pid]}\])?: %{GREEDYDATA:[log][message]}" }
        tag_on_failure => ["_syslog_parse_failure"]
      }
      if [syslog_ts] { date { match => ["syslog_ts","MMM  d HH:mm:ss","MMM dd HH:mm:ss"] remove_field => ["syslog_ts"] } }
    }

    if [process][name] == "sshd" {
      mutate { add_field => { "[event][category]" => "authentication" "[event][module]" => "sshd" } }
      if [log][message] =~ /Accepted/ {
        grok { match => { "[log][message]" => "Accepted %{WORD} for %{USERNAME:[user][name]} from %{IP:[source][ip]}" } tag_on_failure => [] }
        mutate { add_field => { "[event][outcome]" => "success" } }
      } else if [log][message] =~ /Failed/ {
        grok { match => { "[log][message]" => "Failed %{WORD} for (?:invalid user )?%{USERNAME:[user][name]} from %{IP:[source][ip]}" } tag_on_failure => [] }
        mutate { add_field => { "[event][outcome]" => "failure" } add_tag => ["failed_ssh"] }
      }
    }
    else if [process][name] == "sudo" {
      mutate { add_field => { "[event][category]" => "process" "[event][action]" => "sudo" } }
    }

    if "docker" in [tags] {
      mutate {
        rename => { "container_name" => "[container][name]" }
        rename => { "container_id"   => "[container][id]" }
        add_field => { "[event][module]" => "docker" }
      }
    }

    mutate { add_field => { "[host][os][family]" => "linux" } remove_field => ["@version"] }
  }
}

output {
  if "docker" in [tags] {
    opensearch { hosts => ["http://${OPENSEARCH_HOST}"] index => "forensic-linux-%{+YYYY.MM.dd}" }
  } else if "syslog" in [tags] or "linux" in [tags] or [@metadata][pipeline] == "linux" {
    opensearch { hosts => ["http://${OPENSEARCH_HOST}"] index => "forensic-linux-%{+YYYY.MM.dd}" }
  }
}
