{
 "title": "Velociraptor Linux (Full)",
 "tags": [
  "velociraptor",
  "linux",
  "full",
  "dfir"
 ],
 "panels": [
  {
   "title": "Auth events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "_index:velociraptor-linux-* AND artifact:Custom.Linux.Auth.ForensicFull"
    }
   ]
  },
  {
   "title": "Network connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "_index:velociraptor-linux-* AND artifact:Custom.Linux.Network.ForensicFull"
    }
   ]
  },
  {
   "title": "Linux DFIR (Full)",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 4 },
   "targets": [
    { "query": "_index:velociraptor-linux-*" }
   ]
  }
 ]
}