apiVersion: 1

datasources:
  - name: HELK-Elasticsearch
    type: elasticsearch
    uid: helk-es
    access: proxy
    url: http://helk-elasticsearch:9200
    isDefault: false
    jsonData:
      esVersion: "7.10.0"
      timeField: "@timestamp"
      logMessageField: message
      logLevelField: level
      maxConcurrentShardRequests: 5
      interval: Daily
      timeInterval: 10s
